<?php
return array(
    'invalid_params_boardname' => '请输入分区名称',
    'invalid_params_boardid'   => '参数错误[boardid]',
    'disable_delete_systemzone' => '默认分区不能删除',
    'zone_not_exists' => '分区不存在或已被删除',
	'zone_has_children' => '请先删除该分区下的子版块',

	'zone_create_failure' => '分区创建失败',
    'zone_create_success' => '分区创建成功',

	'zone_update_failure' => '分区更新失败',
    'zone_update_success' => '分区更新成功',

    'zone_delete_failure' => '分区删除失败',
    'zone_delete_success' => '分区删除成功',

    'zone_user_update_failure' => '分区负责人更新失败',
    'zone_user_update_success' => '分区负责人更新成功',
    
    'board_lost_params_target' => '请选择需要合并的目标分区',
    'board_lost_params_boardid' => '请选择需要合并的源分区',
	'disable_meger_systemzone' => '不能把默认分区合并到其他分区',
    'target_board_not_exists' => '目标分区不存在或已被删除',
    'board_is_same' => '源分区与目标分区相同！',

    'board_merge_failure'  => '分区合并失败',
    'board_merge_success'  => '分区合并成功',

	'zone_user_select_null' => '你尚未选择分区负责人？'

);