<?php
return array(
    'cln' => '：',
    'total' => '共',
    'number' => '个',
    'oam_sh_info' => '增值电信业务经营许可证：沪B2-20100004',
    'oam_gd_info' => '粤ICP备09187954号',
    'oam_register_info' => 'Copyright &copy; 2002-2011 Oray. All Rights Reserved.',

    'page' => '页',
    'first_page' => '首页',
    'up_page' => '上一页',
    'down_page' => '下一页',
    'last_page' => '末页',

    'add_user' => '添加帐号',
    'accounts' => '帐号',
    'department' => '组织架构',
    'system_role' => '权限',
	'user_group' => '群组',
	'zone_board' => '版块分区',
	'system_general' => '基本信息',
	'system_safe' => '系统安全',

	'logout' => '退出',
	'login_foreground' => '登录前台',
	'suggestions_feedback' => '反馈建议',
	'download_system_manual' => '下载用户手册',
	'services_center' => '客服中心',
	'login_page_setting' => '登录页设置',

    'save' => '保存',
    'user_not_exists' => '用户不存在或已被删除'

);