<?php
return array(
    'select_query_object' => '选择查询对象',
    'percent'  => '进度',
    'nothing_to_query' => '没有可供查询的对象',
    'search_item' => '搜索到',
    'record_num' => '的图度共有',
    'caledndar_download' => '下载查看',
    'finish_time' => '完成时间',
    'tudu_user' => '图度用户',

    'search_cal' => '按日历查询',
    'cal_sun' => '日',
    'cal_mon' => '一',
    'cal_tues' => '二',
    'cal_wed' => '三',
    'cal_thurs' => '四',
    'cal_fri' => '五',
    'cal_sat' => '六'
);