<?php
return array(
    'chat_log' => '聊天记录',
    'chat_log_with' => '与 %s 的聊天记录',
    'chat_log_null' => '暂时没有该用户的聊天记录',
    'select_contact' => '从右侧选择联系人查看相关聊天记录',

    'non_group' => '我的好友',

    'disscuss_group' => '讨论组',

    'search_result' => '搜索结果',
    'search_condition' => '搜索条件',

    'current_user' => '当前用户',
    'all_user' => '所有用户',

    'all' => '所有',
    'nearly_week' => '最近一周',
    'nearly_month' => '最近一个月',
    'nearly_3month' => '最近三个月',

    'search_hint' => '请输入关键字搜索',
    'search' => '搜索',

    'delete_records' => '删除记录',
    'delete_record' => '删除本条记录',
    'delete_log_success' => '删除聊天记录成功',
    'delete_log_failed' => '删除聊天记录失败',
    'delete_action_error' => '未知操作类型，请刷新页面重试！',
    'invalid_chatlogid' => '参数错误[logid]'
);