<?php
return array(
    'label_manage' => '标签管理',
    'system_label' => '系统标签',
    'user_label'   => '自定义标签',
    'create_label' => '新建标签',
    'show' => '显示',
    'hide' => '隐藏',
    'rename' => '重命名',
    'label_name' => '标签名称',
    'folder_name' => '文件夹名称',
    'unread_tudu' => '未读图度数',
    'total_tudu'  => '总图度数',
    'operation'   => '操作',

	'input_new_name' => '请输入新的标签名称',

    'invalid_labelid' => '参数错误[lid]',

	'missing_name' => '缺少标签名称',

	'params_invalid_char'  => '不允许使用 %s 字符。 请尝试使用其他名称',
    'params_invalid_name'  => '%s标签名称无效。系统保留标签',
    'params_label_exists'  => '所选标签名已存在。 请试用其他名称',

    'deny_system_label' => '不能对系统标签执行该操作',

    'label_create_failure' => '标签创建失败',
    'label_create_success' => '标签创建成功',

    'label_update_failure' => '标签操作失败',
    'label_update_success' => '标签操作成功',
    
    'label_delete_failure' => '标签删除失败',
    'label_delete_success' => '标签删除成功',
    
    'label_sort_success' => '标签排序成功',
    'label_sort_failure' => '标签排序失败',

    'show_has_content' => '有内容时显示',
    'operation_label_ways' => '左侧显示方式',
    'left_middle_parenthes' => '[',
    'right_middle_parenthes' => ']',
	'operate_failure' => '操作失败',
    'operate_success' => '操作成功'
);