<?php
return array(
	'title'    => '图度',
	'net_busy' => '网络繁忙',

    'failure'  => '登陆失败',
    'locked'   => '该帐户已被锁定，请联系管理员',
    'success'  => '登陆成功',
    'params'   => '缺少用户名或密码',
    'notexist' => '用户不存在或已被删除',
    'unsupport'=> '您的帐户尚未开通图度系统功能，请联系管理员',
    'timeout'  => '登录超时，请重新登录',
    'seccode'  => '输入验证码无效',
	
	'login_title' => '登录我的橄榄邮',
	'account' => '用户名',
	'password' => '密&nbsp;&nbsp;&nbsp;码',
	'version' => '版&nbsp;&nbsp;&nbsp;本',
	'login' => '登  录',
	
	'remember' => '记住我的用户名',

	'zh_CN' => '简体中文',
	'zh_TW' => '繁體中文',
	'en_US' => 'English',
	
);