<?php
return array(
    'upload_file' => '上传文件',
    'rename'      => '重命名',
    'move_to'     => '移动到...',
    'download'    => '下载',
    'root_folder' => '根目录',
    'uploading'   => '正在上传文件',
    'nd_space'    => '网盘空间',
    'total'       => '共',
    'avalible'    => '可用',
    'up_folder'   => '返回上层目录',

    'create_folder' => '新建文件夹',
    'file_name' => '文件名',
    'file_size' => '大小',
    'upload_time' => '上传时间',

    'deny_foldername' => '%s为系统目录保留名称，不能使用',
    'delete_not_null_folder' => '请先删除文件夹下的所有文件，再删除文件夹',
    'file_list_null' => '当前目录下没有文件',
    'could_not_moveto_current_folder' => '文件已在目标目录下',

    'folder_not_exists' => '文件夹不存在或已被删除',
    'folder_exists' => '文件夹 "%s" 已经存在',
    'folder_create_success' => '文件夹创建成功',
    'folder_create_failure' => '文件夹创建失败',
    'folder_rename_success' => '文件夹重命名成功',
    'folder_rename_failure' => '文件夹重命名失败',
    'folder_delete_success' => '文件夹删除成功',
    'folder_delete_failure' => '文件夹删除失败',
    'missing_folder_name' => '请输入文件夹名称',

    'file_not_exists' => '文件不存在或已被删除',
    'file_exists' => '文件 "%s" 已经存在',
    'file_delete_success' => '文件删除成功',
    'file_delete_failure' => '文件删除失败',
    'file_rename_success' => '文件重命名成功',
    'file_rename_failure' => '文件重命名失败',
    'file_move_success'   => '文件移动成功，立即<a href="/netdisk/?folderid=%s" target="main">查看</a>',
    'file_move_failure'   => '文件移动失败',
    'invalid_file_name'   => '文件和文件夹名称不能包含 *,?,|,\,/,",:,\',&lt;,&gt;字符',

    'ajax_upload_hint' => '请点击“浏览”选择本地文件上传',
    'flash_upload_hint' => '请点击“浏览”选择本地文件上传',
    'uploading_hint' => '等待文件传输，请不要刷新或关闭本页面。',
    'upload_success' => '文件上传成功',
    'upload_failure' => '文件上传失败',
    'go_on_upload' => '继续上传文件',

    'sys_folder' => array(
        'pic' => '我的图片',
        'doc' => '我的文档'
    ),
    
    'share_failure' => '共享失败',
    'share_success' => '共享成功',
    'config_share'  => '设为共享',
    'cancel_share' => '取消共享',
    'edit_share_member' => '编辑共享人群',
    'share_folder' => '共享文件夹',
    'save_failure' => '保存失败',
    'save_success' => '保存成功'
);