<?php
return array(
    'select_query_object' => 'Select people',
    'percent'  => 'Progress',
    'nothing_to_query' => 'No body to query',
    'search_item' => 'Search ',
    'record_num' => ' Tudu have ',
    'caledndar_download' => 'Download',//下载查看
    'finish_time' => 'Finish Time',//完成时间
    'tudu_user' => 'Tudu User',//图度用户

    'search_cal' => 'Caledndar',//按日历查询
    'cal_sun' => 'Sun',
    'cal_mon' => 'Mon',
    'cal_tues' => 'Tues',
    'cal_wed' => 'Wed',
    'cal_thurs' => 'Thur',
    'cal_fri' => 'Fri',
    'cal_sat' => 'Sat'
);