<?php
return array(
    'chat_log' => 'Chat history', //聊天记录
    'chat_log_with' => 'chat history with %s', //与 %s 的聊天记录
    'chat_log_null' => 'No chat history found', //暂时没有该用户的聊天记录
    'select_contact' => 'Select a contact from right side to view chat history', //从右侧选择联系人查看相关聊天记录

    'non_group' => 'My friends',

    'disscuss_group' => 'Discuss',

    'search_result' => 'Result',
    'search_condition' => 'Condition',

    'current_user' => 'Current',
    'all_user' => 'All users',

    'all' => 'All',
    'nearly_week' => 'nearly a week',
    'nearly_month' => 'nearly a month',
    'nearly_3month' => 'nearly 3 months',

    'search_hint' => 'Input keyword to search',
    'search' => 'Search',

    'delete_records' => 'Delete records',
    'delete_record' => 'Delete this record',
    'delete_log_success' => 'Delete success',
    'delete_log_failed' => 'Delete failed',
    'delete_action_error' => 'Error action, please to refurbish this page',//未知操作类型，请刷新页面重试！
    'invalid_chatlogid' => 'Parameter error [logid]'
);