<?php
return array(
    'you' => 'you',
    'login_tudu' => 'Login tudu', //登录图度
    'help' => 'Help',
    'sequence_no' => 'No.',

    'compose' => 'New tudu', //创建图度
    'contacts' => 'Contacts', //通讯录
    'board_home' => 'Boards', //'版块首页',
    'tudu_talk' => 'TuduTalk',
    'my_mailbox' => 'Mailbox',
    'note' => 'Note',
    'quick_mailbox' => 'Mailbox',
    'netdisk' => 'Netdisk',
    'calendar' => 'Calendar',
    'allday'   => 'All day',
    'admin' => 'Manage Tudu',
    'suggest' => 'Suggestion',

    'yes' => 'Yes',
    'no' => 'No',

    'label' => 'Tag', //标签
    'label_inbox' => 'Inbox', //图度箱
    'label_starred' => 'Starred', //星标关注
    'label_todo' => 'Todo',
    'label_sent' => 'Sent', //已发送
    'label_forwarded' => 'Frowarded', // 我转发
    'label_ignore' => 'Ignore', //忽略
    'label_notice' => 'Notice', //公告
    'label_discuss' => 'Discuss', //讨论
    'label_meeting' => 'Meeting',
    'label_all' => 'All tudu', //所有图度
    'label_drafts' => 'Drafts', //草稿箱
    'label_done' => 'Completed', //已完成
    'label_review' => 'Review',
    'label_reviewed' => 'Reviewed',
    'label_wait' => 'Pendding',
    'label_associate' => 'Associate',

    // 日期类
    'date_today' => 'Today', //今天
    'date_tomorrow' => 'Tomorrow', //明天
    'date_mon' => 'Mon', //周一
    'date_tue' => 'Tue', //周二
    'date_wed' => 'Wed', //周三
    'date_thu' => 'Thu', //周四
    'date_fri' => 'Fri', //周五
    'date_sat' => 'Sat', //周六
    'date_sun' => 'Sun', //周日
    'date_format' => '%Y-%m-%d %H:%M', //%Y年 %m月 %d日 %H:%M

    'weather_today' => '',
    'weather' => ' Weather', //天气
    'current' => 'Current', //当前
    'humidity' => 'Humidity', //湿度
    'change_area' => 'Change', //更换城市
    'curr_local' => 'Weather of', //当地
    'weather_null' => 'Unavailable', //未能获得当地天气信息
    'weather_loading' => 'Loading...', //正在加载天气信息

    // 分页
    'page_page'  => 'Page', //页
    'page_next'  => 'Next', //下一页
    'page_prev'  => 'Previous', //上一页
    'page_first' => 'First', //第一页
    'page_last'  => 'Last', //最后一页

    // 其他
    'tudu'      => 'Tudu', //图度
    'discuss'   => 'Discuss', //讨论
    'meeting'   => 'Meeting', //讨论
    'notice'    => 'Notice', //公告
    'board'     => 'Board', //板块
    'post'      => 'Reply', //回复
    'tudu_group'=> 'Tudu group',

    'me'        => 'Me', //我
    'multi_accepter' => 'Many',
    'config'    => 'Settings', //设置
    'logout'    => 'Logout', //退出
    'tuduindex' => 'Tudu home', //图度首页
    'search'    => 'Search tudu', //搜索图度
    'advsearch' => 'Advanced search', //高级搜索
    'logout'    => 'Logout', //退出
    'browse'    => 'Browse',
    'submit'    => 'Submit', //提交
    'save'      => 'Save', //保存
    'confirm'   => 'Confirmation', //确认
    'cancel'    => 'Cancel', //取消

    'suspend'   => 'Suspend',
    'confirm'   => 'OK', //确定
    'unread'   => 'Unread', //未读
    'read'     => 'Read', //已读
    'login_timeout' => 'Log out', //登录超时
    'back'      => 'Back', //返回
    'ignore'    => 'Ignore', //忽略
    'accept'    => 'Accept', //接受
    'refuse'    => 'Refuse', //拒绝
    'forward'   => 'Forward', //转发
    'reply'     => 'Reply', //回复
    'reference' => 'Quote', //引用
    'modify'    => 'Modify', //修改
    'delete'    => 'Delete', //删除
    'copy'      => 'Copy',  // 复制
    'content'   => 'Content', //内容
    'find'      => 'Find', //查找
    'subject'   => 'Title', //标题
    'status'    => 'Status', //状态
    'language'  => 'Language', //语言
    'display'   => 'Display', //显示
    'contact'   => 'Contact', //联系人
    'group'     => 'Group', //群组
    'unassigned'=> 'Not assign', //不指定
    'file_upload' => 'Upload', //文件上传
    'upload' => 'Upload', //上传
    'before' => 'Before', //之前
    'among' => 'Among', //其中
    'search_tudu' => 'Search tudu', //搜索图度
    'search_result' => 'Search result', //搜索结果
    'tudu_homepage' => 'Tudu home', //图度首页
    'general' => 'General', //常规
    'account' => 'Account', //帐户
    'change_skin' => 'Skin', //换肤
    'mailbox_bind' => 'Mailbox',
    'group_manage' => 'Contact Group',
    'folder_and_label' => 'Folder & Tags', //文件夹和标签
    'tudu_rule' => 'Tudu rule', //图度规则
    'my_label' => 'Tags', //我的标签
    'total' => 'Total', //共
    'date' => 'Date', //日期
    'map' => 'Map', //地图
    'tudu_board' => 'Quick boards', //图度板块
    'task_list' => 'Worksheet', //工作表
    'commend_func' => 'Recommended', //推荐功能
    'new_tudu' => 'New tudu', //最新图度
    'tudu_unit'   => '', //个
    'picture' => 'Picture', //图片
    'ontop' => 'Top',
    'close' => 'Close',
    'retry' => 'Retry',
    'disabled' => 'Disabled',
    'link' => 'Link',
    'auth_code' => 'Auth Code',
    'operation' => 'Operation',
    'attendee' => 'Attendee',
    'locate' => 'Locate',

    'unread_tudu' => ' unread', //未读图度
    'starred_tudu' => ' starred', //星标图度
    'lock_screen' => 'Lock screen', //锁屏
    'lock_tips' => 'Lock screen tips', //锁屏提示
    'not_specify' => '-- None --',

    'lock_tips_title' => 'Tudu will enter a locked state', //您的图度将进入锁定状态
    'lock_tips_1' => '+ Tudu will remain online', //? 图度将仍保持在线
    'lock_tips_2' => '+ Before enter the correct "password", deny access', //? 在输入正确的“登录密码”前任何人都无法动您的图度
    'lock_tips_3' => '+ This Makes your tudu more secure', //? 可以更安全的保护您的隐私
    'never_show_hint' => 'Never show this dialog box', //不再显示此对话框
    'unlock_auth_success' => 'Unlock authentication successful', //解锁验证成功
    'unlock_auth_failure' => 'Wrong password, after three times wrong, you will be forced out', //错误密码，三次输入错误，你将会被退出图度登录
    'unlock_auth_forbid'  => 'Account is disabled, please contact the administrator to resolve', //你的帐号已经被禁用，请联系管理员解决
    'account_lock_tips' => 'Password wrong more than %d times, account will be locked', //密码输入错误超过%d次，账号就会被锁定。


    'join_user'=> 'Related', //参与人
    'accept_user' => 'Recipient', //接收人
    'sendtome' => 'Mine', //我执行
    'cctome'   => 'CC', //被抄送
    'sendbyme' => 'Initiated', //我发起

    'notice_is_null' => 'No notice available', //暂时没有公告

    'select_contact' => 'Select a contact', //选择联系人
    'select_group'   => 'Select a group', //选择用户群组
    'dept_cast' => 'Department address book', //部门通信录

    'search_group' => 'Search group...', //查找群组...
    'search_user'  => 'Search user...', //查找用户...

    'create_tudu' => 'New tudu', //创建图度
    'addrbook' => 'Public address book', //公共通讯录
    'chat_history' => 'Chat history', //聊天记录
    'send_tudu' => 'Send Tudu', //发送图度
    'send_discuss' => 'New discuss', //发起讨论

    'tudu_adv_search' => 'Advanced search', //图度高级搜索

    'cln' => ':', //
    'comma' => ',', //
    'title_receiver' => 'Recipient:',//执行人:
    'title_sender'   => 'Sender:', //发起人:
    'title_cc'       => 'CC:', //抄送:
    'title_status'   => 'Status:', //状态:
    'title_starttime'=> 'Begin:', //开始日期:
    'title_elapsed'  => 'Elapsed time:', //耗时:
    'title_endtime'  => 'End:', //截止日期:
    'title_progress' => 'Completed:', //完成率:
    'title_location' => 'Location:', //位置:
    'title_keyword'  => 'Key word:', //关键字:
    'title_folder'   => 'Folder:', //文件夹:
    'title_time'     => 'Time:', //时间:
    'title_board'    => 'Board:', //板块:
    'title_accept_user' => 'Recipient:', //接收人:

    'lang_zh_cn' => '简体中文', //简体中文
    'lang_zh_tw' => '繁體中文', //繁體中文
    'lang_en_us' => 'English', //English

    'timezone' => 'Time zone', //时区
    'hour' => 'Hour', //小时
    'year' => 'Year', //年
    'month' => 'Month', //月
    'day' => 'Day', //日
    'days' => 'Days',
    'weekend' => 'weekend',
    'workday' => 'workday',

    'file_upload_success' => 'File uploaded success', //文件上传成功
    'file_upload_failure' => 'File %s uploaded failure', //文件"%s"上传失败
    'file_upload_null' => 'File had not been selected', //'没有选择上传的文件',
    'file_not_exists' => 'File exists', //文件不存在
    'file_deny_access' => 'You can\'t access the file', //你不能访问该文件
    'file_too_large' => 'File "%s" size exceeds the limit, please upload a file less than "%s"',//文件 "%s" 超过限制大小，请上传 "%s" 以下的文件
    'invalid_file_type' => 'Invalid file type',//不支持上传的文件类型

    'permission_denied_for_tudu' => 'You are permission is denied to current operation',

    'create_tudu' => 'New tudu', //发表图度
    'create_discuss' => 'New discuss', //发起讨论
    'create_notice' => 'New notice', //发布公告
    'create_board' => 'New board', //创建板块

    'board_list' => 'Board list', //板块列表

    'forbid_access' => 'System has been shut down, please check this later or contact the administrator', //系统已关闭，请稍候访问，或联系管理员开通

    'good_morning' => 'Good morning', //上午好
    'good_afternoon' => 'Good afternoon', //下午好
    'good_evening' => 'Good evening', //晚上好

    'week_1' => 'Monday', //星期一
    'week_2' => 'Tuesday', //星期二
    'week_3' => 'Wednesday', //星期三
    'week_4' => 'Thursday', //星期四
    'week_5' => 'Friday', //星期五
    'week_6' => 'Saturday', //星期六
    'week_0' => 'Sunday', //星期日
    'week_end' => 'Weekend', //周末

    'tudu_status_0' => 'Not started',//未开始
    'tudu_status_1' => 'Running',//进行中
    'tudu_status_2' => 'Completed',//已完成
    'tudu_status_3' => 'Rejected',//已拒绝
    'tudu_status_4' => 'Cancelled',//已取消
    'tudu_expire_finish' => 'Expire finished',//超期完成

    'around_month' => 'Around a month',
    'around_week'  => 'Around a week',

    'starttime' => 'Start time',
    'endtime'   => 'End time',
    'time'      => 'Time',

    'tudutalk_install' => 'Install TuduTalk',
    'tudutalk_install_hint' => 'Dear %s,Please download TuduTalk at first if you would like to chat online with others.',
    'install_now' => 'Install',

    'never_remind'     => 'Never Remind',
    'remind_next_time' => 'Remind me next time',

    'mailbox_login_failure' => '"%s"Login failure, please check you email account and password.<a href="/email/modify?address=%s">[change password]</a>',
    'select_inbox_failure'  => '"%s" Read inbox info failure',

    'success' => 'Success',
    'failure' => 'Failure',

    'subject_class' => 'Category', //主题分类
    'add_tpl_list' => 'Load template', //加载模板

    'tudu_need_confirm' => 'Need Confirm', //完成需确认

    'login_log' => 'Login log',//登录日志

    'ip_exception_tips' => 'Last login local is %s，If some question <a href="/setting/log" target="main" style="color:#ffffff">browse logs</a>',

    'tudu_web' => 'Tudu',//图度官网
    'tudu_help' => 'Help',//图度帮助
    'give_feedback' => 'Feedback',//意见反馈
    'tudu_weibo' => 'Weibo',//官方微博

    'invite' => 'Invite', //邀请

    'time_expired' => 'Timeout',
    'time_plan' => 'Plan',
    'time_none' => 'No Limit',
    'time_ahead' => 'Ahead',
    'tudu_version' => 'Version',//版本号

    'apply_for_review' => 'Review',// 申請審批
    'attach_save_to_nd' => 'Save to netdisk',    //保存到網盤
    'space_not_enough' => 'Space not enough',
    'file_is_in_here' => 'File has already exists',//文件已存在

    'claim' => 'Claim',//认领
    'await_claim' => 'Wait claim',//待认领

    'top_add_mailbox' => '+Add mailbox',//添加邮箱
    'add_attention_board' => '+Add quick board',//添加快捷版块
    'board_manage' => 'Board shortcut',  //管理版块

    'tags_manage' => 'Tag manage',  // 管理標籤
    'more_labels' => 'More', //更多标签

    'tudu_help_book' => 'User guide',//下载用户手册

    'new_win' => 'New Window', //新窗口
    'new_win_tips' => 'Open in new window',//新窗口打开

    'set_attention_board' => 'Setting quick board',//设置版块快捷
    'set_bind_mailbox' => 'Binding mailbox',//设置邮箱绑定

    'tudu_flows' => 'Tudu Flows',//图度工作流
    'higher_review' => 'Higher review',//上級審批
    'flow_chart' => 'Chart',//流程图
    'mailbox' => 'Mailbox'//邮箱
);