<?php
return array(
    'contact_search' => 'Please enter a keyword to search', //请输入关键词搜索
    'contact_unit' => 'Unit', //个

    'true_name' => 'Fullname', //姓名
    'department' => 'Department', //部门
    'user_position' => 'Job title', //职位
    'email_addr' => 'E-mail address', //邮箱地址
    'tel_num' => 'Telephone number', //电话号码
    'mobile' => 'Mobile phone', //手机号码
    'email_address' => 'E-mail address', //邮件地址
    'tudu_account' => 'Tudu Account',
    'birthday' => 'Birthday', //出生日期
    'constellation' => 'Constellation', //星座
	'avatar' => 'Avatar', //头像
	'fax' => 'Fax', //传真
	'corporation' => 'Corporation',//公司
	'address' => 'Address',//地址
    'view_chat_record' => 'Chat history', //聊天记录
    'contact_chat' => 'Start chat', //即时聊天
    'contact_tudu' => 'Releated tudu', //往来图度
	'more_info' => 'More information',//添加更多信息
    'group_name' => 'Name',

    'personal_addrbook' => 'Personal address book', //个人通信录
	'create_group' => 'Create group',  //新建联系组
	'edit_contact' => 'Edit contact',   //新建联系人
	'contact_group' => 'Contact group',//联系组
	'year' => 'year', //年
	'month' => 'month', //月
	'day' => 'day', //日
	'remark' => 'remark', //备注
	'secondary_email' => 'Secondary email', //备用邮箱
	'must_tips' => '*',  //（*必填）
	'email_tips' => '(Receive tudu from this email)',  //（系统默认本邮箱接收图度任务）
	'edit_info' => 'Edit information', //编辑资料
	'empty_contact_info' => 'Contact not found', //没有相关的联系人
	'delte_group' => 'Delte group',
	'create_contact' => 'Create contact', //新建联系人
	'add_into_group' => 'Add into group...', //添加到组...
	'edit_group' =>'Edit group', //編輯組
	'search_contact' => 'Search contact', //搜索联系人
	'edit_contact_group' => 'Edit contact group', //编辑联系组
	'missing_name' => 'Please enter your contact name', //姓名必填
	'email_error' => 'Please enter a valid email', //请输入正确的邮箱地址
	'invalid' => 'Parameter error',//参数错误

	'save_fail' => 'Save failed',
	'save_success' => 'Save successfully',
	'delete_fail' => 'Delete failed',
	'delete_success' => 'Delete successfully',
	'empty_group_name' => 'Please enter a group name',
	'operate_success' => 'Successful operation',
	'add_fail' => 'Add failed',
	'update_fail' => 'Update successfully',
    'confirm_delete_group' => 'Confirm to delete contact group selected?',

	'avatar_change' => 'Change', //更改
	'avatar_modify' => 'Avatar modify',//头像编辑
    'avatar_upload_tips' => '(Please click on the "Browse" on your computer, select the photos you want to upload.)',//（请点击“浏览”，在您电脑中选择您要上传的照片。）
    'avatar_thumb' => 'Thumbnail',//缩略图
    'select_photo' => 'Select photo',//选择照片
    'upload_now' => 'Upload Now',//立即上传

    'avatar_filesize_too_large' => 'Avatar filesize limit "%s"',//头像文件限制大小为 "%s"
    'invalid_img_type' => 'Invalid image format, please upload gif, jpg or png image',//无效的图片格式，请上传 gif, jpg 或 png图片
    'avatar_upload_failure' => 'Avatar upload failed',//头像文件上传失败
    'avatar_upload_success' => 'Avatar upload successful',//头像上传成功
    'avatar_edit_failure' => 'Picture file saved failed',//头像文件保存失败
    'avatar_edit_success' => 'Picture file saved successfully',//头像文件保存成功

    'group_ungroup' => 'Ungrouped',
    'group_nearly'  => 'Nearly contact'
);