<?php
return array(
    'perm_deny_create_flow' => 'You do not have permission to create the flow',//你没有创建工作流的权限
    'perm_deny_update_flow' => 'You do not have permission to update the flow',//您没有更新工作流的权限
    'flow_not_exists' => 'Flow does not exist or has been deleted',//你访问的工作流不存在或以被删除
    'flow_content_tips' => '注：员工使用该工作流来创建图度任务时，以上内容会自动加载',//注：员工使用该工作流来创建图度任务时，以上内容会自动加载
    'flow_elapsedtime' => 'Elapsedtime',//所需时间
    'flow_subject' => 'Subject',//工作流名称
    'flow_description' => 'Description',//工作流描述
    'flow_description_tips' => '',//50字符以内文字描述
    'avaliable' => 'Avaliable',//可用人群
    'flow_day' => 'day',//日
    'flow_day_tips' => '（Setting elapsedtime）',//（可设置该工作流的所需时间）
    'return_list' => 'Back',//返回列表
    'create_flow' => 'Create flow',//新建工作流
    'search_flows' => 'Search flow',//搜索工作流
    'serach_keywords_tips' => 'Keywords',//工作流关键字
    'serach_button' => 'Serach',//搜索
    'search_rs_null' => 'Flow not found',//搜索不到与此相关的数据
    'params_invalid_flow_subject' => 'Please enter a valid subject',//请输入正确的工作流名称
    'create_flow_success' => 'Create flow success',//新建工作流成功
    'create_flow_failed' => 'Create flow failure',//新建工作流失败
    'update_flow_success' => 'Update flow success',//更新工作流成功
    'update_flow_failed' => 'Update flow failure',//更新工作流失败
    'delete_flow_success' => 'Delete flow success',//删除工作流成功
    'delete_flow_failed' => 'Delete flow failure',//删除工作流失败
    'description' => 'Description',//描述
    'setting_flow_steps' => 'Setting step',//步骤设置
    'create_flow_steps' => 'Create step',//新建步骤
    'please' => 'Please',//请
    'flow_steps_null' => 'Steps Null',//步骤为空
    'steps_subject' => 'Subject',//步骤名称
    'invalid_flowid' => 'Parameter error [flowid]',//参数错误[flowid]
    'flow_isvalid_delete' => 'Can not this flow, because this flow used in Tudu task',//图度工作流正在使用中，不允许删除

    'next_step' => 'Next',//下一步
    'step_start' => 'Start',//开始
    'step_end' => 'End',//结束
    'modify_settings' => 'Edit',//修改设置

    'flow_null' => 'Flow is null',//该工作流为空
    'params_invalid_flow_steps' => 'Please enter flow steps'//请先设置工作流步骤
);