<?php
return array(
    'YES' => 'Yes',
    'NO'  => 'No',
    'CONFIRM' => 'OK', //确定
    'CANCEL' => 'Cancel', //取消
    'SAVE' => 'Save', //保存
    'DISCARD' => 'Discard', //放弃
    'DELETE' => 'Delete', //删除
    'REPLY' => 'Reply', //回复
    'REPLY' => 'Send reply', //回复
    'REFERENCE' => 'Quote：', //引用：
    'FLOOR' => 'Floor', //楼
    'RENAME' => 'Rename',
    'HINT' => 'Hints',
    'FIRST_POST' => 'Owner', //楼主
    'GROUP' => 'Group', //群组
    'FORWARD' => 'Forward',
    'FORWARD_INFO' => '{0} Forward to {1}', 'POSTING_DATA' => 'Submitting data...', //正在提交数据...
    'NOTHING_SELECTED' => 'No item selected', //没有选中的项目
    'PROCESSING_ERROR' => 'Error occur', //程序处理错误
    'LOCK_SCREEN_TIPS' => 'Tudu has been LOCKED, please enter your login password to unlock', //您的图度进入锁屏状态，请输入图度登录密码解锁
    'TUDU_PWD' => 'Tudu password', //图度密码
    'ADD_DIVIDE' => 'Add New',
    'SAVE_CHANGE' => 'Save',
    'CLN' => ',', //：
    'CLOSE' => 'Close',
    'FILE' => 'File',
    'SPEED' => 'Speed',
    'WAITING_UPLOAD' => 'Waiting',
    'UPLOADED' => 'Uploaded',
    'READ' => 'Read',
    'UNREAD' => 'Unread',
    'WAIT' => 'Wait',
    'SUCCESS' => 'Success',
    'FAILURE' => 'Failure',
    'LEAVE_HINT' => 'Hints',
    'COMPOSE_EXIT_WITHOUT_SAVE' => 'The content had not be saved, leave this page?',
    'COMPOSE_EXIT_SAVE_HINT' => 'The content had not be saved, save it now?',
    'REPLY_EXIT_SAVE_HINT' => 'The reply had not be sended, send it now?',
    'CREATE_BOARD' => 'Create board',
    'MODIFY_BOARD' => 'Edit board',
    'BOARD_MUST_CLASSIFY' => 'Must select an subject type',
    'NOT_ANY_CLASSES' => 'No types or subject are null',
    'INHERIT_PARENT' => 'Inherit',
    'TUDU_FOREIGN' => 'Foreign',


    'LEAVE_HINT' => 'Leave hint', //离开提示
    'COMPOSE_EXIT_WITHOUT_SAVE' => 'The content you are editing has not been saved, are you sure to give up?', //你编辑的内容还没有保存，确定放弃正在编辑的内容吗？
    'COMPOSE_EXIT_SAVE_HINT' => 'The content you are editing has not been saved, do you want to save now?', //你编辑的内容还没有保存，是否保存本次修改？
    'REPLY_EXIT_SAVE_HINT' => 'The reply you are editing has not been sent, do you want to send now?',
    'CREATE_BOARD' => 'New board', //创建板块
    'MODIFY_BOARD' => 'Modify board', //编辑板块
    'BOARD_MUST_CLASSIFY' => 'The category of the board must be selected', //该板块必须选择主题分类
    'NOT_ANY_CLASSES' => 'None category is selected, or the category name is empty', //没有添加任何有效的主题分类，或分类名称都为空，不能强制主题归类
    'INHERIT_PARENT' => 'Inherit',
    'TUDU_FOREIGN' => 'Foreign Manage',

    'CONTACT' => 'Contact',
    'SELECT_CONTACT' => 'Select contact',
    'CONTACT_GROUP' => 'Group',
    'LAST_CONTACT' => 'Nearly',
    'COMMON_CONTACT' => 'Common',
    'PRIVATE_CONTACT' => 'Private',
    'NO_GROUP_CONTACT' => 'No groups',
    'NOT_DELETE_SYSTEM_CONTACT' => 'Can not delete this system contact',//不允许删除企业通讯录的联系人

    'LOADING_LOG' => 'Loading logs...',
    'NOT_ANY_TUDU_DIVIDE' => 'Not any divide Tudu',
    'DIVIDE_MODE_CHANGE_HINT' => 'Divide Tudu had not saved, if switch to simple mode, it will lost some data, really to switch?',//'你还没有保存当前分工，切换到简单模式将丢失完整模式下的部分数据，确定要切换？',
    'SUBMIT_DIVIDE_IN_MODIFY' => 'Some divide Tudu is Modifing, really to save?',
    'LOADING_SUB_TUDU' => 'Loading divide Tudus...',
    'SAVE_DIVIDE_WHILE_UPLOADING' => 'File is uploading, please wait for transfer complete.',
    'CONFIRM_DELETE_DIVIDE' => 'Really to delete this divide Tudu',

    'CONFIRM_TO_DELETE_DRAFTS' => 'The draft will be lost after remove, are you sure to delete?', //草稿删除后将不能恢复，确定要删除选中的草稿？
    'TO_USER_SELECT_MAX_COUNT' => 'Only {0} Recipient(s) can be selected', //执行人最多只能选择{0}个
    'TO_USER_IS_NULL' => 'Please select tudu recipient', //请选择图度执行人
    'INVALID_TO_USER' => 'Invalid user or belong to other organization',  //不能发送到其他组织的图度账号
    'TUDU_SUBJECT_IS_NULL' => 'Please enter the tudu subject', //请输入图度主题

    'SELECT_BOARD_PARENT' => 'Please select a parent area', //请选择所属分区
    'BOARD_NAME_IS_NULL' => 'Please enter the board name', //请输入板块名称
    'BOARD_NOT_APPIONT' => 'Please select board', //请选择所属板块
    'BOARD_MODERATORS_IS_NULL' => 'Please select board moderators', //请选择板块负责人

    'LOADING_ATTACH' => 'Loading attachments ...',
    'FILE_UPLOAD' => 'Upload', //文件上传
    'FILE_UPLOADING' => 'File is uploading ...', //文件正在上传...
    'FILE_UPLOAD_COMPLETE' => 'File transfer complete', //文件传输完毕
    'FILESIZE_EXCEED_LIMIT' => 'File {0} size exceeds the limit, please upload a file less than {1}', //文件 {0} 超过限制大小，请上传 {1} 以下的文件
    'FILESIZE_ZERO_BYTE' => 'File {0} size invalid, just a shortcut?', //文件 {0} 大小不正确或为快捷方式。如果想上传快捷方式指向文件，请单独上传。
    'FILE_UPLOAD_FEILURE' => 'File {0} upload failure',
    'WAITING_UPLOAD' => 'Wait for files to be uploaded', //等待文件上传

    'POST_CONTENT_IS_NULL' => 'Please fill in reply content', //请填写回复内容
    'ELASPED_TIME_IS_NULL' => 'Please fill in how much time consumed', //请填写任务耗时
    'PERCENT_IS_NULL' => 'Please fill in the task progress', //请填写任务进度

    'ADD_REVIEW' => 'Add Reviewer',
    'UPDATE_REVIEW' => 'Update Reviewer',
    'DELETE_REVIEW' => 'Delete Reviewer',

    'CONFIRM_REJECT_TUDU' => 'Are you sure to reject the current tudu?', //确认要拒绝当前图度？
    'CONFIRM_CANCEL_TUDU' => 'Are you sure to cancel the current tudu?', //确认要取消当前图度？
    'CONFIRM_DELETE_TUDU' => 'Are you sure to delete the current tudu?', //确认要删除这些图度？
    'CONFIRM_DELETE_POST' => 'Are you sure to delete the current reply?', //确认要删除这些回复？

    'CONFIRM_CLOSE_BOARD' => 'Confirm to close this board?',
    'CONFIRM_CLEAR_BOARD' => 'Clear board would delete all tudu in this board, really?',
    'CONFIRM_DELETE_BOARD' => 'Confirm to delete this board?',

    'CONFIRM_DELETE_MAILBOX' => 'Are you sure to delete the mailbox?',
    'CONFIRM_DELETE_RULE' => 'Are you sure to delete the rule?',


    'INVALID_TEL_NUMBER' => 'Please enter a valid telephone number', //请输入正确的电话号码
    'INVALID_MOBILE_NUMBER' => 'Please enter a valid mobile number', //请输入正确的手机号码

    'PASSWORD_IS_NULL' => 'Please enter your password', //请输入密码
    'PASSWORD_TOO_SHORT' => 'Password length can not be less than 6 bytes', //密码长度不能小于6位
    'PASSWORD_YES_SPACE' => 'The password cannot contain spaces',//密码不能含有空格
    'PASSWORD_NOT_Byte' => 'Password must be a single-byte characters',//密码必须是单字节的字符
    'PASSWORD_SAFE_LEVEL_MIDDLE' => 'Password length can not be less than 8 bytes, must be a combination of letters and numbers', //密码长度不能小于8位，必须包含字母和数字
    'PASSWORD_SAFE_LEVEL_HEIGHT' => 'Password length can not be less than 8 bytes, must be a combination of letters, numbers and symbols', //密码长度不能小于8位，必须包含字母、数字和符号
    'PASSWORD_NOT_EMPTY' => 'Please enter your private password by TuduTalk',//请输入私密图度密码
    'CONFIRM_PASSWORD_UNMATCH' => 'Passwords do not match',//密码和确认密码不符

    'CONFIRM_DELETE_LABEL' => 'Are you sure to remove this tag?', //确认删除该标签？
    'MISSING_LABEL_NAME' => 'Please enter tag name', //请输入标签名称

    'LOADING_AVATAR_LIBRARY' => 'Loading avatar processing program...', //正在加载头像处理程序...
    'LOADING_CHAT_LOG' => 'Loading chat history ...', //正在加载聊天记录...
    'USER_SELECT_ERROR' => 'User information not exist', //用户不存在或输入错误
    'LOAD_JS_ERROR' => 'Failed to load program, please refresh the page', //程序加载失败，请刷新页面重试

    'TOO_MUCH_OPTION' => 'A maximum number of 20 investigation options can be added', //最多可添加20个调查选项
    'AT_LEAST_TWO_OPTION' => 'At lease 2 investigation options should be preserved', //最少保留两个调查选项

    'NO_SELECTED_OPTION' => 'Please select a option to vote', //请先选择你要投票的选项
    'TOO_MUCH_SELECTED' => 'A maximum number of {0} options can be selected', //最多只能选择{0}个选项

    'CYCLETASK_NEET_ENDTIME' => 'A deadline must be selected in case of repeat cycle', //重复周期必须选择截止日期
    'INVALID_TASK_INTERVAL' => ' Please set correct interval of time', //请设置正确的时间间隔

    'COMPOSE_UPLOAD_FAILURE' => 'Attachment upload failed, are you sure to send a tudu without any attachments?', //有附件上传失败，确定要发送附件缺失的图度吗？
    'REPLY_UPLOAD_FAILURE' => 'Attachment upload failed, are you sure to send a reply without any attachments?', //有附件上传失败，确定要发送附件缺失的回复吗？

    'CONFIRM_DELETE_TUDU' => 'Are you sure to delete this tudu?', //确认删除该图度？

    'TALK_HINT' => 'Please download TuduTalk if you would like to chat online with others',
    'INSTALL_NOW' => 'Install',
    'DONOT_INSTALL' => 'Not yet',

    'RULE_NEET_OPERATION' => 'Please choose an operation when match',
    'RULE_FILTER_VALUE' => 'Invalid filter value',
    'RULE_NO_FILTER' => 'Make sure alivable filter exists. if disable all, please disable the rule.',

    'SWF_INIT_FAILURE' => 'Please install a new version of Flash Player and retry',

    'CONFIRM_DELETE_CONTACT' => 'Are you sure to delete the contact?', //确认删除联系人吗？
    'MISSING_PEOPLE_NAME' => 'Please enter your contact name', //姓名必填
    'MISSING_EMAIL_ADDRESS' => 'Please enter a valid email', //邮箱地址必填

    'MISSING_CONTACT_GROUP_NAME' => 'Please enter a group name', //请输入联系组名称

    'CONFIRM_DELETE_NOTES' => 'Confirm delete notes selected', //确定删除选中的便签？

    'INVALID_CLASS_NAME' => 'Invalid class name', //请输入正确的主题分类名称
    'SAVE_TPL' => 'Save template', //保存模板
    'ADD_TPL' => 'Add template', //添加模板
    'INVALID_TPL_NAME' => 'Please enter a template name', //请输入模板名称
    'INVALID_TPL_CONTENT' => 'Please enter a template content', //请输入模板内容
    'CONFIRM_DELETE_TPL' => 'Confirm delete this template?', //确定删除此模板吗？
    'DELETE_TEMPLATES_TO_DISABLE' => 'Please delete all template at first',
    'TPL_IN_MODIFY' => 'Please save the template which modifing',
    'IMG_UPLOADING' => 'Processing image from clipboard',

    'SELECT_TPL' => 'Select templates', //选择模板
    'LOADING_TPL' => 'Loading templates...', //正在加载模板...
    'NOTHING_TPL' => 'No templates', //没有模板
    'TPL_TIPS'  => 'Select to fill editor', //选择后在任务内容中直接生成模板
    'NETDISK_ATTACH' => 'Netdisk',
    'SELECT_NETDISK_FILE' => 'Select file from your netdisk to send',

    'CONFIRM_DELETE_FILE' => 'Confirm to delete files selected?',
    'CONFIRM_DELETE_FOLDER' => 'Confirm to delete folders selected?',
    'ND_FOLDER_TIPS' => 'Please input folder name',
    'ND_FILE_TIPS' => 'Please input file name',
    'CREATE_FOLDER' => 'New Folder',
    'UPLOAD_CLOSE_HINT' => 'Close this window would cancel upload, close it?',
    'UPLOAD_CANCEL_HINT' => 'Really to cancel this upload',
    'UPLOAD_SUCCESS' => 'Upload success',
    'UPLOAD_ERROR'   => 'Upload failure',
    'SPECE_NOT_ENOUTH' => 'Space not enough',


    'ND_UPLOAD' => 'Uploading',
    'UPLOAD_FILE' => 'Upload',

    'SYS_UPDATE_NOTICE' => 'There are update for tudu system, click here to refresh in order to load update',

    'INVALID_TUDUID'  => 'Parameter error [tid]', //參數錯誤[tid]
    'MISSING_CONTENT' => 'Missing content', //缺少内容
    'SAVE_SUCCESS' => 'Save failed', //保存成功
    'SEND_SUCCESS' => 'Sent successfully', //發送成功

    'AUTOSAVE_TIPS_FIRST' => 'System autosaved TUDU at &nbsp;',//系统自动保存于
    'AUTOSAVE_TIPS_SECOND' => 'minutes before', //分钟前

    'CONFIRM_SEARCH_CALENDAR' => 'Are you sure to search this data, it must be using more time to finish the query ?', //当前查询的数据量较大，可能会导致查询时间缓慢，是否继续？
    'NONE' => 'None', //无

    'MARK_STAR' => 'Attention to star target', //星标关注

    'ADD_CC'      => 'Add cc',
    'ADD_DATE'    => 'Add date',
    'ADD_PERCENT' => 'Edit compeleterate',
    'ADD_DIVIDE'  => 'Add divide',
    'ADD_CONTENT' => 'Show more',
    'ADD_PREV'    => 'Add prepose tudu', //添加前置任务

    'DELETE_CC'      => 'Delete cc',
    'DELETE_DATE'    => 'Delete date',
    'DELETE_PERCENT' => 'Hide compeleterate',
    'DELETE_DIVIDE'  => 'Delete divide',
    'DELETE_CONTENT' => 'Hide advanced',
    'DELETE_PREV'    => 'Hide prepose tudu',//隐藏前置任务
    'HIDE' => 'Hide',

    'VIEW_INVITE' => 'Invite',
    'INVITE' => 'Invite',//邀请
    'INVITE_INFO' => '{0} invite {1} join this meeting',

    'NOT_IGNORE_TUDU' => 'Can not ignore this Tudu',//該圖度不能忽略

    'PREV_TUDU_NOT_EXOSTS' => 'Prepose tudu had been deleted',
    'CYCLE_PREV_TUDU_ID' => 'Prepose tudu invalided',
    'PREV_IS_SELF' => 'Could not select self for Perpose',

    'REVIEW' => 'Review',//審批
    'REVIEW_MORE' => 'In turn ',//依次
    'REVIEW_INFO' => ' %s to review this application',//由 {0} 對本任務進行審批
    'REVIEW_CONFIRM' => 'Review confirm',
    'ADD_REVIEWER' => 'Add Reviewer',

    'CONFIRM_TO_REVIEW_DISAGREE' => 'Are you sure to <strong class="red">disagree</strong> this application ?', //您确定不同意该申请吗？
    'CONFIRM_TO_REVIEW_AGREE' => 'Are you sure to <strong class="green">agree</strong> this application ?',  //您确定同意该申请吗？

    'TUDU_MODIFY_PRIVACY_TIPS' => 'This board is privacy, you create this Tudu is privacy in this privacy board',   //该版块为私密版块，版块下的图度默认为私密

    'TUDU_DIVIDE_ACCEPTER_TIPS' => 'Can not delete this accepter, because this accepter has already create Tudu group or you is accepter in creating and editing Tudu group',  //不能对已有分工的执行人进行删除或创建及修改图度组时执行人必须包含本人

    'TUDU_ACCEPTER_EMAIL_ERROR' => 'Accepter must be email',//執行人輸入格式有誤
    'INDERTERMINATE' => 'Indeterminate',  //待定
    'NETDISK' => 'Netdisk',
    'SAVE_TO' => 'Save to',
    'PLEASE_SAVE_TO' => 'Please save this file to',  //请选择文件保存到
    'CONFIRM_CANCEL_SHARE_TIPS' => 'After cancel this share, all member can not visit this, are you sure to cancel this share ?', //取消后，共享人群均不可访问该文件夹，是否确认取消？

    'TUDU_CLAIM_ACCEPTER_LESS_THAN_ONE' => 'Accepter less than one, because this tudu is claim mode',//您已該勾選圖度為認領模式，執行人必須為多個

    'TEL' => 'Telephone',//电话
    'MOBILE' => 'Mobile',//手机
    'SEND_MSG' => 'Send message',//发送消息
    'SEND_TUDU' => 'Send tudu',//发送图度
    'USER_CARD_INFO' => 'User info',//详细资料
    'USER_ISNULL' => 'User nonexistent', //用户不存在

    'LABEL_NAME' => 'Label name',    //标签名称
    'CREATE_LABEL' => 'Create label',//新建标签
    'CANCEL_LABEL' => 'Cancel label',//取消标签
    'CANCEL_STAR' => 'Cancel star',   //取消星标关注

    'CONFIRM_RESET_VOTE' => 'Are you sure to reset this vote ?', //確定要重置本次投票嗎？
    'TAGS_MANAGE' => 'Tag manage',  //管理标签

    'CAPTURER_UPLOAD_FILE_ERROR' => 'Upload failure',//截屏文件上传错误
    'CAPTURER_START_UPLOAD_ERROR' => 'Initialize screen snap tools error, please to refurbish this page',//截屏插件初始化错误，请刷新页面重试
    'CAPTURER_INSTALL_TIPS' => 'Install screen snap tools',//插件安装提示
    'CAPTURE_FAILURE' => 'Capture failure',
    'INSTALL_ONLINE' => 'Install Online',//在线安装
    'UNINSTALL_CAPTURER_TOOLS_TIPS' => 'Your computer is not install this screen snap tools',//您还未安装图度在线截屏工具
    'CAPTURER' => 'Screen snap',//截屏
    'USE_CAPTURER_NOW' => 'to use screen snap tools',//即可进行截图
    'AFFTER_INSTALL' => 'After installing',//安装后
    'CLICK' => 'click',//点击
    'COMMA' => ',',
    'REVIEW_SUGGEST' => 'Suggestion can be null',

    'INSTALL_LEAVE_CONFIRM' => 'Input will not save, really to leave this page?',

    'VOTE_DETAIL_INFO' => 'Vote information',//投票详细情况

    'ADD_BCC' => 'Add bcc',//添加密送
    'DELETE_BCC' => 'Delete bcc',//刪除密送
    'ADD_TOPTIME' => 'Add top',//添加置頂
    'DELETE_TOPTIME' => 'Delete top',//刪除置頂

    'CREATE_BOARD_CLASS' => 'Create classes',//新建主题分类
    'BOARD_CLASS_SUBJECT' => 'Class subject',//主题分类名称

    'VOTE_OPTIONS' => 'Optinos',//选项
    'VOTE_VOTER' => 'Party',//参与人

    'VOTER_NULL_TIPS' => 'No person select this option',//没有人选择该项

    'UPLOAD_INVALID_SESSION' => 'Invalid Session, Please refresh to retry',

    'SET_FAVOR_BOARD' => 'Set favor',
    'SEARCH_NULL_RESULT' => 'Nothing matched',

    'CONFIRM_DELETE_FLOW' => 'Confirm delete this flow?',//您确定要删除此工作流吗？
    'CONFIRM_DELETE_STEP' => 'Confirm delete this step?',//您确定要删除此步骤吗？
    'DESCRIPTION' => 'Description',//描述
    'STEP_SUBJECT' => 'Subject',//步骤名称
    'INSERT_TO' => 'Insert to',//插入到
    'STEP_TYPE' => 'Tpye',//步骤类型
    'SET_STEP_INFO' => 'Step Info',//设置步骤信息
    'EXECUTE' => 'Execute',//执行
    'START' => 'Start',//开始
    'AFTER_LINE' => '',//之后
    'STEP_RETURN' => 'Return',//打回
    'STOP_FLOW' => 'Stop',//终止流程
    'IF_REVIEWER_DISAGREE' => 'If reviewer disagree',//若审批人不同意则
    'IF_RECEIVER_REJECT' => 'If receiver reject',//若执行人拒绝则
    'REVIEW_TYPE' => 'Review type',//审批方式
    'SELECT_REVIEW_TYPE' => '选择审批方式',
    'HIGHER_REVIEW' => 'Higher review',//上级审批
    'ASSIGN_REVIEWER' => 'Assign reviewer',//指定审批人
    'NEXT' => 'Next',//下一步
    'PREV' => 'Back',//上一步
    'TUDU_CLAIM_TIPS' => '',//勾选后，该图度的执行人则为认领人，且认领人唯一
    'TUDU_CLAIM_MODE' => 'Claim mode',//认领模式
    'SELECT_RECEIVER' => 'Select receiver',//选择执行人
    'PARAMS_INVALID_STEP_SUBJECT' => 'Please enter a valid subject',//请输入正确的步骤名称
    'PARAMS_INVALID_STEP_DESCRIPTION' => 'Please enter a valid description',//请输入正确的描述内容
    'PARAMS_INVALID_REVIEW_TYPE' => 'Please select review type',//请选择审批方式
    'PARAMS_INVALID_REVIEWER' => 'Please select reviewer',//请选择审批人
    'PARAMS_INVALID_RECEIVER' => 'Please select receiver',//请选择执行人
    'EDIT' => 'Edit',//修改
    'CREATE_STEP' => 'Create step',//新建步骤
    'PLEASE' => 'Please',//请
    'STEP_NULL' => 'Steps Null',//步骤为空
    'REVIEWER' => 'Reviewer',//审批人
    'FLOW_SAVE_LEAVE_CONFIRM' => 'Flow will not save, really to leave this page?',//你的工作流还没有保存，是否确定离开？
    'CHART' => 'Chart',//流程圖
    'SWITCH_REVIEW_TYPE' => 'Switch review type',
    'SWITCH_EXECUTE_TYPE' => 'Switch execute type',
    'SELECT_TO_TIPS' => 'Can switch squence and syncronize mode',
    'SELECT_REVIEWER_TIPS' => 'Can switch squence and syncronize mode',

    'BOARD_MUST_FLOWONLY_FLOW_NULL' => 'Flow is null in this board, can not create tudu in this board',//该版块下还没有工作流，不可用
    'BOARD_MUST_FLOWONLY' => 'Must select a tudu flow',//该版块仅用于工作流

    'CONFRIM_DELETE_LOG_RECORD' => 'Are you sure to delete this record?',//您确定要删除本条聊天记录吗？
    'DELETE_LOG_RECORD' => 'Delete chat log record',//删除聊天记录
    'DELETE_LOG_RECORD_BY_OTHERID' => '',//删除与当前用户的聊天记录
    'DELETE_ALL' => 'Delete all',//全部删除
    'ONLY_DELETE' => 'Delete',//只删除
    'BEFORE_ONE_DAY' => 'one day ago',//今天之前
    'BEFORE_ONE_WEEK' => 'one week ago',//一周之前
    'BEFORE_ONE_MONTH' => 'one month ago',//一个月之前
    'BEFORE_THREE_MONTH' => 'three months ago',//三个月之前
    'CHAT_LOG_RECORD' => 'chat log record',//的聊天记录

    'DELETING_TUDU' => 'Deleting Tudu, please wait...',

    'TOO_MACH_VOTE' => 'A maximum number of five votes can be selected',//最多只能创建5个投票
    'NOT_LEAST_ONE_VOTE' => 'The vote must be least a vote',//至少保留一个投票调查
    'MISSING_VOTE_TITLE' => 'Missing vote subject',//缺少投票主题
    'MISSING_VOTE_OPTION' => 'Missing vote option',//缺少投票选项

    'APPEND_TO_GROUP' => 'Append to tudu group',//添加到图度组
    'APPEND_GROUP_NULL_TIPS' => 'Please select tudu group',//请选择需要合并的图度组

    'SHOW_FLOOR' => 'Show floor',//点击展开
    'HIDE_FLOOR' => 'Hide floor',//点击收缩
    'FLOOR_IS_NULL' => 'The post is not exists!',//楼层已被删除

    'TUDU_GROUP_NOT_SYNCHRO' => 'Tudu group can not create synchro task!'//图度组不允许设置逐级执行任务，请先删除分工
);