<?php
return array(
    'label_manage' => 'Tag manage', //标签管理
    'system_label' => 'System tags', //系统标签
    'user_label'   => 'Tags', //用户标签
    'create_label' => 'New tag', //新建标签
    'show' => 'Show', //显示
    'hide' => 'Hide', //隐藏
    'rename' => 'Rename', //重命名
    'label_name' => 'Tag name', //标签名称
    'folder_name' => 'Folder name',
    'unread_tudu' => 'Unread tudu', //未读图度数
    'total_tudu'  => 'Total tudu', //总图度数
    'operation'   => 'Operation', //操作

	'input_new_name' => 'Please enter a new tag name', //请输入新的标签名称

    'invalid_labelid' => 'Parameter error[lid]', //参数错误[lid]

	'missing_name' => 'Missing tag name', //缺少标签名称

	'params_invalid_char'  => 'The character of %s is not allowed to use, please try again', //不允许使用 %s 字符。 请尝试使用其他名称
    'params_invalid_name'  => 'Tag name %s invalid, system reserved', //%s标签名称无效。系统保留标签
    'params_label_exists'  => 'The selected tag name already exists, please try again', //所选标签名已存在。 请试用其他名称

    'deny_system_label' => 'The system tag can not be modified', //不能对系统标签执行该操作

    'label_create_failure' => 'Tag create failure', //标签创建失败
    'label_create_success' => 'Tag create success', //标签创建成功

    'label_update_failure' => 'Tag update failure', //标签操作失败
    'label_update_success' => 'Tag update success', //标签操作成功
    
    'label_delete_failure' => 'Tag delete failure', //标签删除失败
    'label_delete_success' => 'Tag delete success', //标签删除成功

    'label_sort_success' => 'Label sort success',
    'label_sort_failure' => 'Label sort failure',

	'show_has_content' => 'Display this in content',//有内容时显示
    'operation_label_ways' => 'Display usage',//左侧显示方式
    'left_middle_parenthes' => '[',
    'right_middle_parenthes' => ']',
	'operate_failure' => 'Operate failure',//操作失败
    'operate_success' => 'Operate success'//操作成功
);