<?php
return array(
    'upload_file' => 'Upload',
    'rename'      => 'Rename',
    'move_to'     => 'Move to...',
    'download'    => 'Download',
    'root_folder' => 'Root',
    'uploading'   => 'Uploading',
    'nd_space'    => 'Space',
    'total'       => 'Total',
    'avalible'    => 'Usable',
    'up_folder'   => 'Go up',

    'create_folder' => 'New folder',
    'file_name' => 'File name',
    'file_size' => 'Size',
    'upload_time' => 'Upload time',

    'deny_foldername' => '%s is name for system folder',
    'delete_not_null_folder' => 'Please delete all of file of this folder',
    'file_list_null' => 'No files',
    'could_not_moveto_current_folder' => 'File is in the folder',

    'folder_not_exists' => 'Folder not exists or had been deleted',
    'folder_exists' => 'Folder "%s" already exists',
    'folder_create_success' => 'Folder create success',
    'folder_create_failure' => 'Folder create failure',
    'folder_rename_success' => 'Folder rename success',
    'folder_rename_failure' => 'Folder rename failure',
    'folder_delete_success' => 'Folder delete success',
    'folder_delete_failure' => 'Folder delete failure',
    'missing_folder_name' => 'Please ',

    'file_not_exists' => 'File not eixtsts',
    'file_exists' => 'File "%s" is exists',
    'file_delete_success' => 'File delete success',
    'file_delete_failure' => 'File delete failure',
    'file_rename_success' => 'File rename success',
    'file_rename_failure' => 'File rename failure',
    'file_move_success'   => 'File move success, <a href="/netdisk/?folderid=%s" target="main">browse</a>',
    'file_move_failure'   => 'File move failure',
    'invalid_file_name'   => 'Filename could not contain *,?,|,\,/,",:,\',&lt;,&gt;',

    'ajax_upload_hint' => 'Click “browse” to select file to upload',
    'flash_upload_hint' => 'Click “browse” to select file to upload',
    'uploading_hint' => 'Waiting upload, please don\'t refresh',
    'upload_success' => 'File upload success',
    'upload_failure' => 'File upload failure',
    'go_on_upload' => 'Continue upload',

    'sys_folder' => array(
        'pic' => 'My picture',
        'doc' => 'My files'
    ),
    
    'share_failure' => 'Share failure',//共享失败
    'share_success' => 'Share success',//共享成功
    'config_share'  => 'Share',//设为共享
    'cancel_share' => 'Cancel share',//取消共享
    'edit_share_member' => 'Edit share people',//编辑共享人群
    'share_folder' => 'Share folder',  //共享文件夹
    'save_failure' => 'Save failed',//保存失败
    'save_success' => 'Saved successfully'  //保存成功
);
