<?php
return array(
    'create' => 'Create',  //新建
    'my_note' => 'My note', //我的便签
    'note_contene' => 'Contents of your note', //便签内容
    'null_note' => 'Nothing of your note', //还没有便签

    'color_yellow' => 'Yellow',
    'color_red'    => 'Red',
    'color_blue'   => 'Blue',
    'color_green'  => 'Green',
    'color_purple' => 'Purple',
    'color_gray'   => 'Gray',

    'tudu_subject' => 'Tudu Subject'
);