<?php
return array(
    'rule' => 'Rule',//规则
    'rule_status' => 'Status',//状态
    'operation' => 'Operation',//操作
    'create_rule' => 'Create Rule',//创建收发规则
    'my_rule' => 'My Rule',//我的收发规则
    'rule_on' => 'Start using',//启用
    'rule_off' => 'Stop',//停用

    'rule_switch' => '启用规则',
    'condition_title' => '收发图度时，如果',
    'then_title' => '则执行',
    'tudu_accepter' => 'Rcpt',//执行人
    'tudu_cc' => 'CC',//抄送人
    'tudu_sender' => 'Sender',//发起人
    'mark_label' => '标记标签',

    'rule_keyword' => array(
        'if' => 'If',//如果
        'contain' => 'contain',//包含
        'exclusive' => 'exclusive',//不包含
        'from' => 'sender',//发起人
        'to' => 'recipient',//执行人
        'cc' => 'cc',//抄送人
        'subject' => 'subject',//标题
        'then' => 'then',//则
        'label' => 'add label',//添加标签
        'starred' => 'add starred',//标记星标关注
        'ignore' => 'ignore'//直接忽略
    ),

    'label_deleted' => '标签已被删除',
    'rule_affect_title' => '是否作用于现有图度',
    'rule_affect_tips' => '您是否对现有的图度执行此规则？',
    'wait_for_rule_affect' => '收发规则正在更新现有图度，请稍候查看结果',
    'rule_tips' => '通过过滤条件，系统会自动将收发的图度标记或忽略，方便分类管理',

    'rule_not_exists' => '收发规则不存在或已被删除',
    'rule_create_success' => '创建收发规则成功',
    'rule_create_failure' => '创建收发规则失败',
    'rule_update_success' => '更新收发规则成功',
    'rule_update_failure' => '更新收发规则失败',
    'rule_delete_success' => '删除收发规则成功',
    'rule_delete_failure' => '删除收发规则失败',

    'board_sum' => 'Counted board',//版块汇总
    'already_add_remind_board' => '已添加提醒板块',
    'mailbox' => 'Mailbox',//邮箱
    'apply_board' => 'Apply board',//应用板块
    'high_grade' => 'Advanced',//高级
    'more_setting' => 'More Setting',//更多设置
    'mail_remind' => 'Mail remind',//邮件提醒
    'mail_remind_tips' => '(可设置多个邮箱，用分号隔开)',
    'mail_remind_operation' => '收到图度时，邮件提醒',
    'mailbox_null_tips' => '请输入接收邮件提醒的邮箱',
    'invalid_mailbox_address' => '邮箱格式有误，请检查设置后再提交'
);