<?php
return array(
    'account_setting' => 'Account Settings',//帐户设置
    'default_lang' => 'Language',//默认语言选项
    'default_timezone' => 'Time zone',//默认时区设置
    'default_timeformat' => 'Date format',//默认日期格式
    'goback_account' => 'Return to account settings',//返回帐户设置
    'change_password' => 'Change password',//修改密码
    'current_password' => 'Current password',//您当前的密码
    'input_new_password' => 'New password',//填写您的新密码
    'input_re_password' => 'Confirm new password',//确认新密码
    'tudu_profile' => 'Show every reply',//图度回复用户信息
    'profile_all' => 'Display picture, name and title',//显示头像、姓名和职称
    'profile_name' => 'Show only the name',//仅显示姓名
    'only_display' => 'Show only',//只显示
    'tudu_recently' => 'days of tudu',//天内的图度
    'all' => 'all',//所有

    'password_tips' => 'Please enter no less than 6 characters, must contain letters, numbers and special symbols',//请输入不少于6位字符，必需包含字母、数字和特殊符号
    'user_info_tips' => 'Please contact the administrator to modify this part of the information',//请联系管理员修改此部分资料
    'change_password_tip' => 'Modify the password and remember your new password',//修改密码后请谨记您的新密码
    'password_tips' => 'Change your password here, please do a re-login after doing this',//修改您的密码，设置成功后再次登录图度需要使用新码密码，请牢记密码。

    'user_status_1' => 'Confirmed',//正式
    'user_status_0' => 'Disabled',//停用
    'user_status_2' => 'Trial',//试用

    'confirm_password_unmatch' => 'Passwords do not match',//密码和确认密码不符
    'old_password_unmatch' => 'The password you gave is incorrect',//当前密码不匹配

    'password_level_not_match_0' => 'Must have at least 6 characters',//密码不得少于6位字符
    'password_level_not_match_1' => 'Must have at least 8 characters, must contain letters and numbers',//密码不得少于8位字符，必需包含字母和数字
    'password_level_not_match_2' => 'Must have at least 8 characters, must contain letters, numbers and symbols',//密码不得少于8位字符，必需包含字母、数字和符号

    'update_config_success' => 'User settings updated successfully',//成功更新用户设置
    'userinfo_update_success' => 'User information saved successfully',//用户信息保存成功
    'password_update_failure' => 'Password update failed',//密码更新失败
    'password_update_success' => 'Password updated successfully',//密码更新成功
    'save_change' => 'Save changes',//保存更改

    'in_tudu_list' => 'Tudu list',//在图度列表中
    'pagesize' => 'Every page display',//每页显示
    'recommand' => 'Recommended',//推荐
    'reply_unit'   => '',//条
    'in_reply_list' => 'Tudu Reply list',//图度回复数

    'post_sort' => 'View posts sort',
    'invert_posts' => 'Inverst',
    'sequence_posts' => 'Sequence',

    'tel' => 'Telephone',//固定电话
    'mobile' => 'Mobile',//手机
    'birthday' => 'Birthday',//出生日期
    'idnumber' => 'ID Number',//证件号码
    'nick' => 'Nickname',//昵称
    'avatar' => 'Avatar',//头像
    'gender' => 'Gender',//性别
    'position' => 'Job title',//职位信息
    'functions' => 'Opening function',//开启功能
    'user_status' => 'Account status',//帐户状态
    'truename' => 'Real name',//真实姓名
    'accountname' => 'Account name',//帐户名称

    'avatar_modify' => 'Avatar modify',//头像编辑
    'avatar_upload_tips' => '(Please click on the "Browse" on your computer, select the photos you want to upload.)',//（请点击“浏览”，在您电脑中选择您要上传的照片。）
    'avatar_thumb' => 'Thumbnail',//缩略图
    'select_photo' => 'Select photo',//选择照片
    'upload_now' => 'Upload Now',//立即上传


    'avatar_filesize_too_large' => 'Avatar filesize limit "%s"',//头像文件限制大小为 "%s"
    'invalid_img_type' => 'Invalid image format, please upload gif, jpg or png image',//无效的图片格式，请上传 gif, jpg 或 png图片
    'avatar_upload_failure' => 'Avatar upload failed',//头像文件上传失败
    'avatar_upload_success' => 'Avatar upload successful',//头像上传成功
    'avatar_edit_failure' => 'Picture file saved failed',//头像文件保存失败
    'avatar_edit_success' => 'Picture file saved successfully',//头像文件保存成功

    'user_detail_info' => 'Details information',//详细资料
    'user_base_info' => 'Basic information',//基本资料

    'timezone_GMT-12' => '[GMT +12:00] New Zealand',//新西兰
    'timezone_GMT-11' => '[GMT +11:00] Central Pacific',//太平洋中部
    'timezone_GMT-10' => '[GMT-10:00] Western Pacific',//西太平洋
    'timezone_GMT-9' => '[GMT+9:00] Tokyo, Japan',//日本 东京
    'timezone_GMT-8' => '[GMT+8:00] Beijing, Chongqing, Hong Kong',//中国标准时间 北京，重庆，香港
    'timezone_GMT-7' => '[GMT+7:00] Bangkok, Thailand',//泰国 曼谷
    'timezone_GMT-6' => '[GMT+6:00] Central Asia',//中亚
    'timezone_GMT-5' => '[GMT+5:00] West Asia',//西亚
    'timezone_GMT-4' => '[GMT+4:00] Arab',//阿拉伯
    'timezone_GMT-3' => '[GMT+3:00] Russia',//俄罗斯
    'timezone_GMT-2' => '[GMT+2:00] Egypt',//埃及
    'timezone_GMT-1' => '[GMT+1:00] Rome, Italy',//意大利 罗马
    'timezone_GMT+0' => '[GMT+0:00] Greenwich Mean Time',//格林威治标准时间
    'timezone_GMT+1' => '[GMT-1: 00] Azores',//亚速尔
    'timezone_GMT+2' => '[GMT-2: 00] Mid-Atlantic',//大西洋中部
    'timezone_GMT+3' => '[GMT-3: 00] South East',//南美洲东部
    'timezone_GMT+4' => '[GMT-4: 00] Canada',//加拿大
    'timezone_GMT+5' => '[GMT-5: 00] Eastern United States and Canada',//美加东部
    'timezone_GMT+6' => '[GMT-6: 00] Mexico',//墨西哥
    'timezone_GMT+7' => '[GMT-7: 00] MST',//美国山区
    'timezone_GMT+8' => '[GMT-8: 00] Pacific',//太平洋
    'timezone_GMT+9' => '[GMT-9: 00] Alaska',//阿拉斯加
    'timezone_GMT+10' => '[GMT-10: 00] Hawaii',//夏威夷
    'timezone_GMT+11' => '[GMT-11: 00] Samoa',//萨摩亚
    'timezone_GMT+12' => '[GMT-12: 00] International Date Line',//国际日期变更线

    'skin_tips' => 'Click image to switch directly to the skin, after switching, the settings are automatically saved.',//点击图片即可直接切换皮肤，切换后，设置自动保存。

    'password_deny_to_demoaccount' => 'You\'re using demo account,could not change password',


    'skin_0' => 'Green',
    'skin_1' => 'Pink',
    'skin_2' => 'Chinese red',
    'skin_3' => 'Gray',
    'skin_4' => 'Coffee',
    'skin_5' => 'Blue',
    'skin_6' => 'Purple',
    'skin_7' => 'Black',
    'skin_8' => 'Deep green',
    'deny_change_skin' => 'Deny to change skin',

    'init_password' => 'Change the password',
    'init_pwd_hint1' => 'Your password had been initilaize;',
    'init_pwd_hint2' => 'Change it in order to prevent thief.',
    'new_password' =>'Password',
    'confirm_password' =>'Confirm',

	'one_week_login_log' => 'Login log in nearly a 30 days',//最近 1 周内的登录日志
    'null_login_log' => 'Nothing about login log',//没有相关日志
    'login_time' => 'Login time',//登录时间
    'login_source_ip' => 'IP source',//来源IP
    'login_ip_address' => 'IP location',//IP所在地
    'unknow_ip' => 'Unknown IP', //未知IP
    'unknow_ip_address' => 'Unknown', //未知

    'font_settings' => 'Font Settings',//字体大小
    'default_fontfamily' => 'Font Family',//默认字体设置
    'default_fontsize' => 'Font Size',//默认字体大小
    'simsun' => 'SimSun',//宋体
    'nsimsun' => 'NSimsun',//新宋体
    'fangsong_GB2312' => 'FangSong_GB2312',//仿宋_GB2312
    'kaiti_GB2312' => 'KaiTi_GB2312',//楷体_GB2312
    'simhei' => 'SimHei',//黑体
    'microsoft_yahei' => 'Microsoft YaHei',//微软雅黑

    'invalid_email' => 'Invaid email address'//您设置的邮箱格式有误，请重新填写
);