<?php
return array(
    // 界面文字
    'signas' => 'Mark as',//标记为
    'belong_board' => 'Board',//所属版块
    'select_board' => '--Select board--',//--选择版块--
    'label_total' => 'Total <span id="tudu-total">%s</span> tudu',//共  %s 个图度
    'label_unread' => 'In %s a total of %d',//在 "%s" 中共有 %d 个
    'cc' => 'CC',//抄送
    'view' => 'View:',//查看
    'open_file' => 'Open',//打开
    'execute' => 'Execute',
    'column_accepter' => 'Rcpt',//执行人
    'column_cc'       => 'CC',
    'column_endtime' => 'Deadline',//截止日
    'meeting_time'  => 'Time',
    'column_reply' => 'Reply/View',//回复/查看
    'reply' => 'Reply',//回复
    'confirm_tudu' => 'Confirm',//确认
    'cancel_done' => 'Cancel confirm',//取消确认
    'close_discuss' => 'Close discussion',//关闭讨论
    'reopen_discuss' => 'Reopen discussion',//重开讨论
    'subject' => 'Subject',//主题
    'sender' => 'Sender',//发起人
    'endtime' => 'Deadline',//截止日期
    'toptime'  => 'On top',
    'percent' => 'Percent',//进度
    'receiver' => 'Recipient',//执行人
    'lastpost' => 'Update',//最后更新
    'download' => 'Download',//下载
    'download_all' => 'Download all',//下载全部
    'attachment' => 'Attachment',//附件
    'netdisk_attach' => 'Netdisk',
    'move_to_inbox' => 'Move to tudu box',//移到图度箱
    'tudulistnull' => 'No tudu found',//暂时没有相关的图度
    'default_sort' => 'Default sort',//返回默认排列
    'select' => 'Select:',//选择：
    'all' => 'All',//全部
    'none' => 'No',//无
    'send' => 'Send',//发送
    'preview' => 'Preview', //预览
    'send_on_time' => 'Regularly send',//定时发送
    'save_draft' => 'Save draft',//保存草稿
    'urgent' => 'Urgent',//紧急
    'private' => 'Private',//私密
    'update_progress' => 'Update progress',//更新进度
    'elapsed' => 'Worked on this for',//耗时
    'mobile_remind' => 'Update notify',//图度Talk提醒
    'remind_all' => 'Notify all',
    'repeat_cycle' => 'Repeat',//重复周期
    'pure_text' => 'Plain text',//纯文本
    'plan_total' => 'Expected %.1f hours',//预计 %.1f 小时
    'real_elapsed' => ' %.1f hours elapsed',//已累计耗时 %.1f 小时
    'tudu_time_notice' => 'This tudu will be expired in %d days.',//本图度在%d天内到期。
    'tudu_timeover_notice' => 'This tudu has expired for %d days.',//本图度已过期 %d 天。
    'post_last_modify' => 'Last edited by %s at %s',//最后由 %s 于  %s 编辑
    'post_floor' => 'F',//楼
    'view_all_post' => 'View all replies',//查看全部回复
    'null_subject' => '(No subject)',//(无主题)
    'add_label' => 'Add tag',//添加标签
    'week' => 'Week',//周
    'add_to_inbox' => 'Add to tudu box',//添加到图度箱
    'cancel_ignore' => 'Cancel ignored',//取消忽略
    'edit_in_newwin' => 'Edit in new window ',//新窗口编辑
    'return_frame' => 'Return to full page',//返回完整页面
    'select_class' => 'Select category',//选择类别
    'my_attention_board' => 'My quick boards',
    'print' => 'Print',
    'log' => 'Logs',
    'invert_posts' => 'Invert',
    'sequence_posts' => 'Sequence',
    'detail' => 'Detail',
    'new_add_divide' => 'Add New',
    'add_review' => 'Add Review',
    'update_review' => 'Edit Review',
    'delete_review' => 'Delete Review',
    'reviewer' => 'Reviewer',
	'accepter_follow' => 'Follow',
    'notify_tips' => 'Notify all when update',
    'percent_100' => 'Set to 100%',
    'wait' => 'Wait',
    'mark_all' => 'Mark all as ',
    'foreign_manage' => 'Foreign access',
    'add_foreign' => 'Add foreign access',
    'switch_gantt_view' => 'Gantt mode',
    'switch_gantt_view' => 'Standard mode',
    'tudu_flow' => 'Flow',
    'load_more_tudu' => 'Load More...',
    'examine' => 'Examine',
    'screencapture' => 'Screen snap',

	'add_cc'      => 'Add cc',
    'add_date'    => 'Add date',
    'add_percent' => 'Edit compeleterate',
    'add_divide'  => 'Add divide',
	'add_content'  => 'Show more',

	'delete_cc'      => 'Delete cc',
    'delete_date'    => 'Delete date',
    'delete_percent' => 'Hide compeleterate',
    'delete_divide'  => 'Delete divide',
	'delete_content'  => 'Hide advanced',

    'meeting_notify_setting' => 'Notify before meeting',
    'meeting_notify_tips'    => 'Notify receiver to prepare before meeting',
    'notify_setting'         => 'Notify',
    'meeting_notify_5min'    => '5 minutes',
    'meeting_notify_10min'    => '10 minutes',
    'meeting_notify_15min'    => '15 minutes',
    'meeting_notify_30min'    => '30 minutes',
    'meeting_notify_1hour'    => '1 hour',
    'meeting_notify_2hour'    => '2 hour',
    'meeting_notify_prev9'    => '9:00 at Last day',
    'meeting_notify_prev14'   => '14:00 at Last day',
    'meeting_notify_prev18'   => '18:00 at Last day',

    //XXX
    'tudu_divide' => 'Divide',
    'divide_unread' => 'There are %s divide Tudus is unread',
    'no_divide' => 'There is no divide',
    'have_child_modifing' => 'There is divide Tudu modifing, please save it at first',
    'delete_not_null_tudugroup' => 'Tudu group "%s" can not be deleted, Please delete divide Tudu of it',
    'params_missing_chtid' => 'There is not any divide Tudu',
    'parent_tudu_not_exists' => 'Divide Tudu choiced is not exists or be deleted',
    'child_tudu_not_exists' => 'Divide Tudu choiced is not exists or be deleted',
    'no_divide_tudu' => 'There is not any divide',
    'accept_before_divide' => 'Please accept Tudu at first',
    'deny_append_tudu_to_group' => 'Can not add an tudu which sent into Tudu group',
    'tudu_group_send_success' => 'Tudu group send success',
	'tudu_group_send_failure' => 'Tudu group send failure',
    'tudu_group_save_success' => 'Tudu group save success',
    'tudu_group_save_failure' => 'Tudu group save failure',
    'child_simple_edit' => 'Switch to smiple mode',
    'child_full_edit' => 'Switch to full mode',
    'save_divide' => 'Save',
    'divide_less_then_one' => 'Divide less then one, If you want to pass the tudu to other one, you can forward it',
    'tudu_is_divide_deny_multi_accepter' => 'Tudu is divided, not support multi accepters',
    'divide_forbid_multi_accepter' => 'There are multi accepters in this Tudu, could not be divided',
    'deny_tudu_group' => 'You had not permission to view',
    'auth_tips' => 'Need a random code for foreign user to acess',
    'foreign_auth' => 'Auth code',
    'remind_tips' => 'Notify all while reply and update',
    //XXX

    'add_prev_tudu'    => 'Add perpose tudu',
    'remove_prev_tudu' => 'Remove perpose tudu',
    'prev_tudu' => 'Perpose tudu',

    'inherit_parent' => 'Inhreit',
    'vote' => 'Vote',//投票调查
    'vote_option' => 'Vote option',//调查选项
    'add_option' => 'Add option',//添加选项
    'max_choice_tips' => 'Choose number of options, 1 of one choice, 0 or leave blank to be unlimited',//设置最多可选数，1为单选，0或不填则无限制
    'option_tips' => 'Keep at least two options',//至少保留两个选项
    'vote_configs' => 'Vote Settings',//调查设置
    'option_content' => 'Options content',//选项内容
    'order_num' => 'Sort',//排序
    'invalid_option_text' => 'Please enter the vote option content',//请输入调查选项内容
    'vote_now' => 'Vote now',//投票
    'already_vote' => 'You have participated in this vote',//您已经参与过本次投票
    'no_selected_option' => 'No vote items selected',//没有选中的投票项目
    'no_selected_tudu' => 'No tudu selected',
    'tudu_group_review' => 'Tudu group can not apply review',
    'no_accepter_apply' => 'Only accepter could apply review',
    'add_reviewer_self' => 'Can not specitify yourself to review next step',
    'disable_review' => 'You could not review this tudu ',
    'vote_is_expired' => 'This vote has expired',//该投票已经过期
    'vote_is_invalid' => 'This vote has expired or disabled',//投票超过期限或已失效
    'vote_is_close' => 'This vote has finished',//本次投票已结束
    'repeat_range' => 'Valid period',//重复范围
    'cycle_mode' => 'Cycle mode',//定期模式
    'cycle_mode_day' => 'By day',//按天
    'cycle_mode_week' => 'By weekly',//按周
    'cycle_mode_month' => 'By month',//按月
    'cycle_tips' => 'Note: The task\'s start date and end date only valid on the current task\'s completion time, nothing to do with periodicity, to set up periodicity, set the repeat date range. ',//注：任务的开始日期\结束日期仅对当前任务完成时间有关，与周期性无关。如要设置任务的周期性请设置重复范围。
    'deadline_none' => 'None',
    'cycle_times' => 'Times',
    'cycle_endtime' => 'End at ',

	'private_tips' => 'Only sender and all receiver can access if marked privacy.',//注：勾选私密任务后，只有发起人、执行人和抄送人才能看到该任务。
	'open_password' => 'Open password',//开启密码
	'open_pwd_tips' => 'Receiver must using password to access.',//&nbsp;&nbsp;（勾选后，执行人和抄送人均需要输入密码才能看到该任务）
	'password_space' => 'The password cannot contain spaces',//密码不能含有空格
	'password_success' => 'Success, loading page...',//密码正确，正在为你跳转...
	'password_error' => 'Password error',//密码错误
	'input_privacy_pwd' =>'Password:',//请输入私密图度密码：
    'password_not_byte' => 'Password must be a single-byte characters',//密码必须是单字节的字符


    'month_week_first' => 'First',//第一个
    'month_week_second' => 'Second',//第二个
    'month_week_third' => 'Third',//第三个
    'month_week_forth' => 'Fourth',//第四个
    'month_week_last' => 'Last',//最后一个
    'work_day' => 'Workday',//工作日
    'cycle_what_days' => 'Days',//日子
    'cycle_every' => 'Every',//每
    'cycle_every_workday' => 'Each work day',//每个工作日
    'cycle_every_complete' => 'When tudu is completed',//每当任务完成后的第
    'cycle_recreate' => ' then re-build task',//重新生成任务
    'cycle_month' => 'Month',//个月
    'cycle_after' => 'Post',//后的
    'cycle_number' => 'First',//的第
    'repeat_cycle_is' => 'Repetition interval',//重复间隔为
    'cycle_tudu' => 'Cycle Repeat',
    'cycle_remind' => 'Cycle Repeat, Repeat time:%s, Avaliable time:%s',//'周期图度 生成时间：%s，生效时间：%s。',
    'cycle_repeat_times' => 'Repeat %d times',//'重复事件%d次',
    'cycle_repeat_week' => 'Every %d weeks %s',//'每%d周后的 %s',
    'cycle_at_0' => 'Last',
    'cycle_at_1' => 'First',
    'cycle_at_2' => 'Second',
    'cycle_at_3' => 'Third',
    'cycle_at_4' => 'Fourth',


    'invalid_endcount' => 'Invalid repetition',//无效的重复次数
    'invalid_enddate' => 'Invalid repeat end date',//无效的重复结束日期
    'discuss_is_closed' => 'Discussion is closed',//讨论已经关闭
    'full_reply_mode' => 'Switch to full reply mode',//切换到完整回复模式
    'board_is_closed' => 'Board is closed',

    'upload_pic' => 'Upload image',//上传图片
    'network_pic' => 'Network image',//网络图片
    'upload_pic_hint' => '(Please click on the "Browse", select your computer to upload your photos.)',//(请点击“浏览”，在您的电脑中选择您要上传的照片。)
    'network_pic_hint' => '(Please fill in the following input box inside the link path to be inserted into the picture.)',//(请在下面输入框里面填上待插入图片的链接路径。)
    'pic_url' => 'Picture path',//图片路径
    'select_pic' => 'Select picture',//选择图片


    'vote_failure' => 'Vote submit failed',//投票提交失败
    'vote_success' => 'Votes submitted successfully',//投票提交成功

	'vote_clear_success' => 'Reset Vote successfully', //重置投票成功
	'vote_clear_failure' => 'Reset Vote failed', //重置投票失敗

    'review_failure' => 'Review failure',
    'review_success' => 'Review Success',

    // 附件单位
    'attach_unit' => '',//个
    'unread_tudu' => ' Unread tudu',//未读图度
    'subject_keyword' => 'Heading keyword',//标题关键字

    'tudu_receiver_info_0' => 'You have not accepted the tudu of %s initiated, please accept.',//你还未接受 %s 发起的图度，请及时接受。
    'tudu_receiver_info_2' => 'You have rejected the task',//你已经拒绝该任务
    'tudu_receiver_info_3' => 'This tudu has confirmed the completion',//该图度已经确认完成
    'tudu_receiver_info_4' => 'Tudu has been canceled',//图度已被取消

    'tudu_info_0' => 'Waiting for %s to accept tudu. ',//正等待  %s 接受图度
    'tudu_info_2' => '%s has rejected this tudu',//%s 已经拒绝该图度
    'tudu_info_3' => 'his tudu has confirmed the completion',//该图度已经确认完成
    'tudu_info_4' => 'Tudu has been canceled',//图度已被取消

    'starttime' => 'Begin',//开始日期
    'endtime' => 'End',//截止日期
    'epalsedtime' => 'Expected',//预计耗时
    'tudu_percent' => 'Progress',//完成率

    'user_post' => 'Show this author only',//只看该作者
    'user_chat' => 'Start a chat',//跟他聊天
    'user_tudu' => 'Create tudu',//发起图度

    'tudu_timeover' => 'Expired',//已超期
    'status_needaccept' => 'Not accepted',//未接受
    'status_waitaccept' => 'Incertitude',
    'status_accepted'   => 'Accepted',
    'status_waitforconfirm' => 'Need confirmed',//需确认
    'need_accept' => 'Need accepted',//需接受

    'longtime_no_update_discuss' => 'Discuss had not update 3 months',
    'longtime_no_update_tudu' => 'Tudu had not update 3 months',
	'longtime_no_confirm_tudu' => 'Tudu had not confirm 3 days',//三天内未确认的任务

    'tudu_status_0' => 'Not started',//未开始
    'tudu_status_1' => 'Running',//进行中
    'tudu_status_2' => 'Completed',//已完成
    'tudu_status_3' => 'Rejected',//已拒绝
    'tudu_status_4' => 'Cancelled',//已取消
    'tudu_status_done' => 'Confirmed',//已确认



    // 参数


    'params_invalid_tuduid' => 'No tudu is specified',//没有指定操作的图度
    'params_invalid_labelid' => 'No tag is specified',//没有指定的标签
    'params_invalid_boardid' => 'Please select the target board',//请选择目标板块
    'params_invalid_postid' => 'No reply is specified to operate',//没有指定操作的回复
    'params_invalid_subject' => 'Please enter the correct subject',//请输入正确的主题
    'params_invalid_post_content' => 'Please enter your reply',//请输入回复内容
    'params_invalid_content' => 'Please enter content',//请输入内容
    'tudu_params_invalid_to' => 'Please specify the tudu recipient',//请指定图度的执行人
    'discuss_params_invalid_to' => 'Please specify the recipient of the discussion',//请指定讨论的接收人
    'user_is_accepter' => '"%s" already was recipient,can not forward',
    'deny_forward_tudugroup' => 'Tudu group deny to forward',
    'batch_update_invalid' => 'Please select at least one tudu enabled to update progress',
    'batch_forward_invalid' => 'Please select at least one tud enabled to forward',
    'confirm_batch_reject' => 'Confirm to reject these tudus?',
    'confirm_batch_accept' => 'Confirm to accept these tudus?',
    'confirm_batch_close' => 'If close this dialog, operation not submit will be canceled, Confirm to close?',

    'user_not_exists' => 'Tudu user "%s" does not exist or has been deleted',//图度用户“%s”不存在或已被删除
    'label_not_exists' => 'Label does not exist or has been deleted',//标签不存在或已被删除
    'board_not_exists' => 'Forum does not exist or has been deleted',//版块不存在或已被删除
    'tudu_not_exists' => 'Tudu does not exist or has been deleted',//图度不存在或已被删除
    'post_not_exists' => 'Reply does not exist or has been deleted',//回复不存在或已被删除
    'user_has_divide' => 'Accepter "%s" had divided tudu, please delete the divides tudu as first',



    // 权限
    'perm_deny_view_tudu' => 'You do not have permission to view the tudu',//你没有查看该图度的权限
    'perm_deny_upload' => 'You do not have permission to upload attachment',//你没有上传附件的权限
    'perm_deny_cancel_tudu' => 'You do not have permission to cancel the tudu',//你没有取消该图度的权限
    'perm_deny_delete_tudu' => 'You do not have permission to delete the currently selected tudu',//你没有权限删除当前选择的图度
    'perm_deny_reject_tudu' => 'You can not reject the tudu',//你不能拒绝该图度
    'perm_deny_accept_tudu' => 'You can not accept the tudu',//你不能接收该图度
    'perm_deny_done_tudu' => 'You can not confirm that the tudu',//你不能确认该图度
    'perm_deny_create_tudu' => 'You do not have permission to create tudu',//你没有发表图度的权限
    'perm_deny_update_tudu' => 'You do not have permission to update the tudu',//你没有更新图度的权限
    'perm_deny_update_task' => 'You do not have permission to update the tudu',
    'perm_deny_update_notice' => 'You do not have permission to update the notice',
    'perm_deny_update_meeting' => 'You do not have permission to update the meeting',
    'perm_deny_update_discuss' => 'You do not have permission to update the discuss',
    'perm_deny_forward_tudu' => 'You do not have permission to forward the tudu',//你没有转发图度的权限
    'perm_deny_update_percent' => 'You do not have permission to update progress',//你没有更新进度的权限
    'perm_deny_create_notice' => 'You do not have permission to create notice',//你没有发表公告的权限
    'perm_deny_create_discuss' => 'You do not have permission to create discussions',//你没有发表讨论的权限
    'perm_deny_create_post' => 'You do not have permission to send reply,',//你没有发表回复的权限
    'perm_deny_update_post' => 'You do not have permission to edit the response,',//你没有编辑回复的权限
    'perm_deny_delete_post' => 'You do not have permission to delete the reply',//你没有删除回复的权限
    'tudu_is_done' => 'The tudu has been completed',//该图度已经完成
    'deny_delete_tudu_sent' => 'You can not delete the tudu that has been sent',//不能删除已经发出的图度
    'perm_deny_to_divide'   => 'Unenable to divide this tudu',    //XXX




    // 操作
    'invalid_tuduid' => 'Parameter error [tid]',//参数错误[tid]
    'invalid_labelid' => 'Parameter error [lid]',//参数错误[lid]
    'invalid_postid' => 'Parameter error [pid]',//参数错误[pid]
    'forbid_save_sent' => 'Can not save a tudu as draft that has been sent',//不能保存已发送过的图度为草稿
    'forbid_non_accepter_forward' => 'The tudu can not be forwarded if you are not the recipient',//非执行人不能转发图度
    'forbid_non_sender_send' => 'A tudu can only send by it\'s creator',//非发起人不能发送图度
    'forbid_forward_myself' => 'Recipient can not forward a tudu to him(her)self',//执行人不能转发给自己
    'forbid_delete_first_post' => 'Subject can not be deleted',//主题内容不允许删除
    'missing_board' => 'Please specify a board of the tudu belongs to',//请指定图度所属版块
    'missing_to' => 'Please specify the tudu recipient',//请指定图度的执行人
    'missing_cc' => 'Please specify the recipient of the tudu',//请指定图度的接收人
    'missing_subject' => 'Missing subject',//缺少主题
    'missing_content' => 'Missing content',//缺少内容
    'add_label_success' => 'Add tag success',//添加标签成功
    'del_label_success' => 'Delete tag success',//删除标签成功
    'remove_label_success' => 'Cancel tag success',//取消标签成功
    'send_failure' => 'Send failed',//发送失败
    'send_success' => 'Sent successfully',//发送成功
    'save_failure' => 'Save failed',//保存失败
    'save_success' => 'Saved successfully',//保存成功
    'delete_failure' => 'Delete tudu fails',//删除图度失败
    'delete_success' => 'Tudu has been successfully deleted',//已将图度成功删除
    'mark_failure' => 'Tudu mark failed',//图度标记失败
    'mark_success' => 'Tudu has been successfully marked',//已将图度成功标记
    'accept_success' => 'Tudu accepted ',//成功接受图度
    'accept_failure' => 'Accept failure',
    'reject_success' => 'Tudu rejected',
    'reject_failure' => 'Reject failure',
    'cancel_success' => 'Tudu canceled',//图度已成功取消
    'state_success' => 'Tudu status updated',//更新图度状态成功
    'state_failure'  => 'Tudu status update failed',//更新图度状态失败

    'ignore_success' => 'Tudu has been ignored.',//图度忽略状态更新成功
    'ignore_failure' => 'Tudu ignore failure',//图度忽略状态更新失败
    'inbox_success' => 'Tudu has been moved to the tudubox',//已经成功移到图度箱
    'tudu_delete_success' => 'Tudu deleted',//图度删除成功
    'tudu_delete_failure' => 'Tudu delete failed ',//图度删除失败
    'post_delete_success' => 'Reply deleted',//回复删除成功
    'post_delete_failure' => 'Reply delete failed',//回复删除失败
    'post_send_failure' => 'Post reply failures',//发表回复失败
    'post_send_success' => 'Post reply success',//已成功发表回复

    'target_board_not_exists' => 'Target board not exists',
    'move_to_current_board' => 'Can not move to current board',
    'deny_to_move_tudu' => 'Deny to move tudu',
    'from_board_not_exists' => 'From board not exists',
    'no_selected_boards' => 'Nothing selected',
    'tudu_move_failure' => 'Move tudu failure',
    'tudu_move_success' => 'Move tudu success',
    'no_reviewer' => 'No input reviewers',

    'remind_time_left' => 'Will expire in %d days,',//将在%d天内到期，
    'remind_unaccepted' => 'You have not accept the tudu send by %s, please confirm in time.',//你还未接受 %s 发给你的图度，请及时确认。
    'remind_expried' => 'Tudu has been expired %s days, please confirm. ',//图度已超期%d天，请及时确认。
    'remind_done' => 'Tudu has been completed, please confirm in time. ',//图度已完成，请及时确认。
    'remind_cancel' => 'Tudu has been canceled, please confirm in time. ',//图度已取消，请及时确认。
    'remind_reject' => 'Tudu has been rejected, please confirm in time. ',//图度已拒绝，请及时确认。
    'send_info' => 'The tudu was sent by %s, to %s,',//本图度由 %s 发送给 %s，
    'forward_info' => 'This tudu was initiated by %s, at %s, %s forwarded to %s.',//本图度由%s发起，在 %s 由 %s 转发给 %s，
    'loading_accepter' => 'Loading tudu accepter list ... ',
    'loading_attendee' => 'Loading tudu attendee list ... ',
    'load_accepter_failure' => 'Load accepter failure, click to reload',
    'remind_meeting_left' => 'Meeting send by %s, start at %s.',
    'remind_meeting_accept' => 'You\'ve not confirm to join, please accept to join.',
    'tudu_unconfirm' => 'Unconfirmed',

    'print_err' => 'Print error, please check you printer',

    'list_group' => array (
        'notice' => 'Notice',//公告
        'await' => 'Pending',//待办
        'doing' => 'Running',//进行中
        'other' => 'Related',//相关
        'done' => 'To confirm',//已完成待确认
        'waitconfirm' => 'Wait confirm',
        'discuss' => 'Discuss',
        'meeting' => 'Meeting',
        'last_week' => 'Last week',//上周
        'more_early' => 'Earlier',//更早
        'today' => 'Today',//今天
        'contact_null' => 'Not specified',//未有指定
        'multi' => 'multi',
        'unaccept' => 'Wait for accept',
        'noendtime' => 'No endtime',
        '7day' => 'Seven days',
        'later' => 'Later',
        'review' => 'Wait review',
        'reviewed' => 'Review done'
    ),

    'wait_review' => 'Waiting',
    'future_review' => 'Future',

    'log_time' => 'Time',
    'log_operator' => 'User',
    'log_detail' => 'Detail',

    // 日誌更新欄位
    'tudu_log' => array(
        'action_create' => 'Create',
        'action_create_group' => 'Create tudu group',
        'action_send'   => 'Create',
        'action_update' => 'Update',
        'action_delete' => 'Delete',
        'action_close'  => 'Close',
        'action_open'   => 'Open',
        'action_done'   => 'Confirm',
        'action_undone' => 'Reopen',
        'action_progress' => 'Update progress',
        'action_accept' => 'Accept',
        'action_cancel' => 'Cancel',
        'action_decline' => 'Decline',
        'action_forward' => 'Forward',
        'action_divide'  => 'Divide',
        'action_invite'  => 'Invite',
        'action_review'  => 'Apply review',
        'action_examine' => 'Review',
        'action_review'  => 'Review',
        'action_apply'   => 'Apply review',

    	'action_claim'   => 'Claim Tudu',
        'claimuser' => 'Claim user',

        'percent' => 'Progress',
        'cc' => 'Add CC',
        'bcc' => 'Add Bcc',
        'accepter' => 'Add Recipient',//添加接收人
        'reviewer' => 'Reviewer',
        'starttime' => 'Start time',
        'endtime' => 'End time',
        'to' => 'Accepter',
        'status' => 'Status',
        'selfstatus' => 'Self status',
        'subject' => 'Subject',
        'totaltime' => 'Total time',
        'agree' => 'Result',

        'percent_suffix' => '%',
        'totaltime_suffix' => 'hours'
    ),

    'invalid_authcode' => 'Authcode error',
    'password_title'   => 'Need a password',
    'password_tips'    => 'Get the password from sender',
    'send_foreigner'   => 'Send to these emails and save them to contacts',
    'foreign_user_already_exists' => 'Foreign receiver "%s" already exists',
    'tudu_sent_success' => 'Tudu sent success',
    'contact_save_as' => 'Save as ',
    'had_not_foreign' => 'Have not this type of foreigner',
    'copy_link' => 'Copy link',

    'add_foreign_failure' => 'Add foreigner failure',
    'add_foreign_success' => 'Add foreigner success',
    'remove_foreign_failure' => 'Delete foreigner failure',
    'remove_foreign_success' => 'Delete foreigner success',
    'foreign_not_exists' => 'Foreign not exists in this tudu',
    'perm_deny_add_foreign' => 'Deny to manage foreigner of current tudu',
    'deny_add_user_to_foreign' => 'Could not add tudu user to foreigner',
    'deny_remove_user_in_foreign' => 'Could not remove tudu user from here',

    'invalid_to_user' => 'Can not send to other organization',  //不能发送到其他组织的图度账号

    'tudu_need_confirm_tips' => '',  //勾选后，当执行人更新进度为100%时，需发起人确认任务完成

    'show_starttime' => 'Display', //显示
    'hide_starttime' => 'Not displayed ', //不显示
    'tudu_display_date' => 'Task date', //任务起始日期
    'show_starttime_tips' => 'Display starttime before subject', //每次生成的循环任务标题前显示任务的发起日期
    'hide_starttime_tips' => 'Not display starttime before subject', //每次生成的循环任务标题前不显示任务的发起日期

    'private_notice' => 'Private notice',  //私密公告
    'private_notice_tips' => 'Sender or accepter can view this private notice',  //私密公告，只有發起人和接收人才能看到本公告

    'file_size' => 'Size',
    'attach_name' => 'Attachment name',
    'attach_poster' => 'Upload user',  //上傳者

    'tudu_attach_list_null' => 'Nothing about attachments in this Tudu',   //該圖度沒有相關附件

    'forbid_non_accepter_invite' => 'Not this meeting participant, you can not invite any user', //非会议参与人不能邀请他人参加会议
    'user_is_meeting_accepter' => '“%s” has already this meeting participant, you can invite this user', //“%s”已经是本会议的参与人，不能邀请

    'preview_gantt' => 'Preview gantt',//预览甘特图
    'gantt_view' => 'Gantt',//甘特图

    'not_save_finish_tudu' => 'Can not update this finish Tudu', //不能更新已终止或确认完成的图度

    'agree' => 'Agree',
    'disagree' => 'Disagree',
    'need_review' => 'Need review',
    'more_review_tudu' => 'More Tudu is already review',  //更多已审批图度
    'agree_edit_hint' => 'Agree this apply after send this tudu', //发送后即同意本申请

    'agree_reply'  => 'Agree apply; <br />Forward to %s review.',
    'agree_reply_to_exec' => 'Agree apply；<br />Forward to %s to carry out',
    'agree_reply_no_next'  => 'Agree apply.',
    'reject_reply' => 'Reject apply; <br />Please modified and apply again.',

    'tudu_group_accepter_must_has_me' => 'Create or edit Tudu group, accepter is yourself',  //創建或修改圖度組執行人必須含有本人

    'attach_save_to_nd' => 'Save to netdisk',    //保存到網盤
    'space_not_enough' => 'Space not enough',

    'file_is_in_here' => 'File has already exists',//文件已存在

    'cancel_starred' => 'Cancel Starred',
    'mark_starred' => 'Mark Starred',

    'tudu_claim_tips' => '', //勾选后，该图度的执行人则为认领人，且认领人唯一
    'tudu_claim_mode' => 'Claim mode', //认领模式
    'claim_info' => 'This tudu was initiated by %s, please claim to %s.',//本图度由 %s 发起，由 %s 进行认领。
    'claim_accepter_info' => 'This tudu was initiated by %s, %s has already claimed.',//本图度由 %s 发起，已由 %s 认领了。
    'claim_accepter_log' => '%s claim this tudu',  //%s认领了该图度。
    'unclaim_accepter_log' => '%s reject this tudu',  //%s拒绝了该图度，该图度重新回到认领状态。
    'tudu_claim_accpeter_less_than_one' => 'Accepter less than one, because this tudu is claim mode',  //您已勾选该图度为认领模式，执行人必须为多个

    'tudu_has_already_claim' => 'This tudu has already claimed, claim failure', //已有用户认领了图度，认领失败
    'step_not_claim' => 'This operation is not claim',//当前操作不是认领步骤
    'tudu_claim_success' => 'Claim success', //认领成功
    'tudu_claim_failure' => 'Claim failure', //认领失败

    'periods_of_time' => 'Periods of time',  //時間段

    'task_priority_tips' => 'Urgency task', //紧急任务
    'task_secrecy_tips' => 'Sender or accepter can view this private task',//私密任务，只有发起人、执行人和抄送人才能看到本任务
    'task_cycle_tips' => '',//勾选后，可为本任务设置重复周期
    'discuss_notifyall_tips' => '',//勾选后，本讨论若进行回复时，均提醒所有接收人
    'notice_notifyall_tips' => '',//勾选后，本公告若进行修改或回复时，均提醒所有接收人
    'meeting_notifyall_tips' => '',//勾选后，本会议若进行修改或回复时，均提醒所有参与人
    'meeting_remindbefore_tips' => '',//可设置会议前提醒参与人准时出席
    'meeting_cycle_tips' => '', //勾选后，可为本会议设置重复周期
    'keep_attach_tips' => 'If contain attachment, it will pass to future tudus.',
    'cycle_keep_attach' => 'Keep attachments',

    'resetvote' => 'Reset vote', //重置投票
    'date_to' => 'to', //到
    'more_vote_option' => 'You can not vote more than %s options in this vote', //本次投票最多只能投 %s 票

    'after_view_vote_result' => '',//投票后结果才可见
    'open_vote_voter' => '',//公开投票参与人
	'vote_ticket' => 'tickets',//人参与投票
    'view_vote_info' => 'Vote information',//查看投票情况
    'single_choice' => 'Simple selection',//单选投票
    'more_choice' => 'Multiple choice',//多选投票
    'choice_maximum' => 'Choose',//最多可选
    'option' => 'options',//项

    'bcc' => 'Bcc',//密送
    'add_bcc' => 'Add bcc',//添加密送
    'add_toptime' => 'Add top',//添加置顶

    'create_board_class' => 'Create classes',//新建主题分类

    'missing_flow_steps' => 'Missing flow steps',//工作流流程为空，不能发送
    'missing_flow_steps_upper_reviewer' => 'Missing upper users',//缺少流程上级审批人员，不能发送
    'missing_upper_reviewer' => 'Missing',
    'missing_flow_steps_receiver' => 'Missing flow receiver',//缺少工作流参与人员，不能发送

    'remind_flow_tips_info' => 'This flow(%s) send by %s.',//本工作流（%s）由 %s 发起。
    'vote_subject' => 'Vote subject',//投票主题
    'add_vote' => 'Add vote',//新增调查
    'reset_vote_tips' => 'Reset vote result',//修改后投票自动清零
    'missing_vote_title' => 'Missing vote subject',//缺少投票主题
    'missing_vote_option' => 'Missing vote option',//缺少投票选项

    'private_discuss_tips' => 'Private discuss',//私密讨论，只有接收人和相关权限人可见
    'private_discuss' => 'Private discuss',//私密讨论
    'unfinish_tudu' => 'unfinish',//未完成图度

    'vote_info' => '%s statistical results',//%s的投票情况
    'vote_result' => 'Votes',//票数
    'vote_percent' => 'Percent',//比例
    'vote_voter' => 'Party',//参与人

    'append_group' => 'Append Group',//添加到组
    'append_tudu_group_failed' => 'Append group failed',//合并到图度组失败
    'append_tudu_group_success' => 'Append group success',//成功合并到图度组
    'target_tudugroup_not_exists' => 'Tudu Group choiced is not exists or be deleted',//目标图度组不存在或已被删除

    'post_remind' => 'Post notify',//回复提醒
    'vote_anonymous' => 'Sender can view voter'//创建人显示投票参与人
);