<?php
return array(
    'select_query_object' => '選擇查詢對象',
    'percent'  => '進度',
    'nothing_to_query' => '沒有可供查詢對象',
    'search_item' => '搜索到',
    'record_num' => '的圖度共有',
    'caledndar_download' => '下載查看',
    'finish_time' => '完成時間',
    'tudu_user' => '圖度用戶',

    'search_cal' => '按日曆查詢',
    'cal_sun' => '日',
    'cal_mon' => '一',
    'cal_tues' => '二',
    'cal_wed' => '三',
    'cal_thurs' => '四',
    'cal_fri' => '五',
    'cal_sat' => '六'
);