<?php
return array(
    'chat_log' => '聊天記錄',
    'chat_log_with' => '與 %s 的聊天記錄',
    'chat_log_null' => '暫時沒有該使用者的聊天記錄',
    'select_contact' => '從右側選擇連絡人查看相關聊天記錄',

    'non_group' => '我的好友',

    'disscuss_group' => '討論組',

    'search_result' => '搜索結果',
    'search_condition' => '搜索條件',

    'current_user' => '當前用戶',
    'all_user' => '所有用戶',

    'all' => '所有',
    'nearly_week' => '最近一周',
    'nearly_month' => '最近一個月',
    'nearly_3month' => '最近三個月',

    'search_hint' => '請輸入關鍵字搜索',
    'search' => '搜索',

    'delete_records' => '刪除記錄',
    'delete_record' => '刪除本條記錄',
    'delete_log_success' => '刪除聊天記錄成功',
    'delete_log_failed' => '刪除聊天記錄失敗',
    'delete_action_error' => '未知操作類型，請刷新頁面重試！',
    'invalid_chatlogid' => '參數錯誤[logid]'
);