<?php
return array(
    'label_manage' => '標籤管理',
    'system_label' => '系統標籤',
    'user_label'   => '自定義標籤',
    'create_label' => '新建標籤',
    'show' => '顯示',
    'hide' => '隱藏',
    'rename' => '重命名',
    'label_name' => '標籤名稱',
    'folder_name' => '資料夾名稱',
    'unread_tudu' => '未讀圖度數',
    'total_tudu'  => '總圖度數',
    'operation'   => '操作',

	'input_new_name' => '請輸入新的標籤名稱',

    'invalid_labelid' => '參數錯誤[lid]',

	'missing_name' => '缺少標籤名稱',

	'params_invalid_char'  => '不允許使用 %s 字元。 請嘗試使用其他名稱',
    'params_invalid_name'  => '%s標籤名稱無效。系統保留標籤',
    'params_label_exists'  => '所選標籤名已存在。 請試用其他名稱',

    'deny_system_label' => '不能對系統標籤執行該操作',

    'label_create_failure' => '標籤創建失敗',
    'label_create_success' => '標籤創建成功',

    'label_update_failure' => '標籤操作失敗',
    'label_update_success' => '標籤操作成功',
    
    'label_delete_failure' => '標籤刪除失敗',
    'label_delete_success' => '標籤刪除成功',

    'label_sort_success' => '標籤排序成功',
    'label_sort_failure' => '標籤排序失敗',

	'show_has_content' => '有內容時顯示',
    'operation_label_ways' => '左側顯示方式',
    'left_middle_parenthes' => '[',
    'right_middle_parenthes' => ']',
	'operate_failure' => '操作失敗',
    'operate_success' => '操作成功'
);
