<?php
return array(
	'title'    => '圖度',
	'net_busy' => '網路繁忙',

    'failure'  => '登陸失敗',
    'locked'   => '該帳戶已被鎖定，請聯繫管理員',
    'success'  => '登陸成功',
    'params'   => '缺少用戶名或密碼',
    'notexist' => '用戶不存在或已被刪除',
    'unsupport'=> '您的帳戶尚未開通圖度系統功能，請聯繫管理員',
    'timeout'  => '登錄超時，請重新登錄',
    'seccode'  => '無效的登錄驗證碼',
	
	'login_title' => '登錄我的橄欖郵',
	'account' => '用戶名',
	'password' => '密&nbsp;&nbsp;&nbsp;碼',
	'version' => '版&nbsp;&nbsp;&nbsp;本',
	'login' => '登  錄',
	
	'remember' => '記住我的用戶名',

	'zh_CN' => '簡體中文',
	'zh_TW' => '繁體中文',
	'en_US' => 'English',
	
);
