<?php
return array(
    'upload_file' => '上傳文件',
    'rename'      => '重命名',
    'move_to'     => '移動到...',
    'download'    => '下載',
    'root_folder' => '根目錄',
    'uploading'   => '正在上傳文件',
    'nd_space'    => '網盤空間',
    'total'       => '共',
    'avalible'    => '可用',
    'up_folder'   => '返回上層目錄',

    'create_folder' => '新建資料夾',
    'file_name' => '檔案名',
    'file_size' => '大小',
    'upload_time' => '上傳時間',

    'deny_foldername' => '%s為系統目錄保留名稱，不能使用',
    'delete_not_null_folder' => '請先刪除資料夾下的所有檔，再刪除資料夾',
    'file_list_null' => '目前的目錄下沒有檔',
    'could_not_moveto_current_folder' => '檔已在目標目錄下',

    'folder_not_exists' => '資料夾不存在或已被刪除',
    'folder_exists' => '資料夾 "%s" 已經存在',
    'folder_create_success' => '資料夾創建成功',
    'folder_create_failure' => '資料夾創建失敗',
    'folder_rename_success' => '資料夾重命名成功',
    'folder_rename_failure' => '資料夾重命名失敗',
    'folder_delete_success' => '資料夾刪除成功',
    'folder_delete_failure' => '資料夾刪除失敗',
    'missing_folder_name' => '請輸入資料夾名稱',

    'file_not_exists' => '檔不存在或已被刪除',
    'file_exists' => '檔 "%s" 已經存在',
    'file_delete_success' => '檔刪除成功',
    'file_delete_failure' => '檔刪除失敗',
    'file_rename_success' => '檔重命名成功',
    'file_rename_failure' => '檔重命名失敗',
    'file_move_success'   => '文件移動成功，立即<a href="/netdisk/?folderid=%s" target="main">查看</a>',
    'file_move_failure'   => '檔移動失敗',
    'invalid_file_name'   => '檔和資料夾名稱不能包含 *,?,|,\,/,",:,\',&lt;,&gt;字符',

    'ajax_upload_hint' => '請點擊“流覽”選擇本地檔上傳',
    'flash_upload_hint' => '請點擊“流覽”選擇本地檔上傳',
    'uploading_hint' => '等待檔案傳輸，請不要刷新或關閉本頁面。',
    'upload_success' => '檔上傳成功',
    'upload_failure' => '檔上傳失敗',
    'go_on_upload' => '繼續上傳檔',

    'sys_folder' => array(
        'pic' => '我的圖片',
        'doc' => '我的文件'
    ),
    
    'share_failure' => '共用失敗',
    'share_success' => '共用成功',
    'config_share'  => '設為共用',
    'cancel_share' => '取消共用',
    'edit_share_member' => '編輯共用人群',
    'share_folder' => '共用文件夾',
    'save_failure' => '保存失敗',
    'save_success' => '保存成功'
);
