<?php
return array(
    'rule' => '規則',
    'rule_status' => '狀態',
    'operation' => '操作',
    'create_rule' => '創建收發規則',
    'my_rule' => '我的收發規則',
    'rule_on' => '啟用',
    'rule_off' => '停用',

    'rule_switch' => '啟用規則',
    'condition_title' => '收發圖度時，如果',
    'then_title' => '則執行',
    'tudu_accepter' => '執行人',
    'tudu_cc' => '抄送人',
    'tudu_sender' => '發起人',
    'mark_label' => '標記標籤',

    'rule_keyword' => array(
        'if' => '如果',
        'contain' => '包含',
        'exclusive' => '不包含',
        'from' => '發起人',
        'to' => '執行人',
        'cc' => '抄送人',
        'subject' => '標題',
        'then' => '則',
        'label' => '添加標籤',
        'starred' => '標記星標關注',
        'ignore' => '直接忽略'
    ),
    
    'label_deleted' => '標籤已被刪除',
    'rule_affect_title' => '是否作用于現有圖度',
    'rule_affect_tips' => '您是否對現有的圖度執行此規則？',
    'wait_for_rule_affect' => '收發規則正在更新現有圖度，請稍候查看結果',
    'rule_tips' => '通過過濾條件，系統會自動將收發的圖度標記或忽略，方便分類管理',
    
    'rule_not_exists' => '收發規則不存在或已被刪除',
    'rule_create_success' => '創建收發規則成功',
    'rule_create_failure' => '創建收發規則失敗',
    'rule_update_success' => '更新收發規則成功',
    'rule_update_failure' => '更新收發規則失敗',
    'rule_delete_success' => '刪除收發規則成功',
    'rule_delete_failure' => '刪除收發規則失敗',

    'board_sum' => '版塊匯總',
    'already_add_remind_board' => '已添加提醒板塊',
    'mailbox' => '郵箱',
    'apply_board' => '應用板塊',
    'high_grade' => '高級',
    'more_setting' => '更多設置',
    'mail_remind' => '郵件提醒',
    'mail_remind_tips' => '(可設置多個郵箱，用分號隔開)',
    'mail_remind_operation' => '收到圖度時，郵件提醒',
    'mailbox_null_tips' => '請輸入接收郵件提醒的郵箱',
    'invalid_mailbox_address' => '郵箱格式有誤，請檢查設置後再提交'
);